<ol class="breadcrumb">
	<li><a href="/"><?= __('Main'); ?> </a></li>
	<li class="active"><?= __('Login or create new account') ?></li>
</ol>

<h2 class="main-heading text-center"><?= __('Login or create new account') ?></h2>

<?php echo $this->getNotices(); ?>

<section class="login-area">
	<div class="row">
		<div class="col-sm-6">
			<div class="panel panel-smart">
				<div class="panel-heading">
					<h3 class="panel-title">
						<?= __('Sign in') ?>
					</h3>
				</div>
				<div class="panel-body">
					<form role="form" method="post" action="/user/login" autocomplete="on">
						<div class="form-group">
							<label><?= __('Login') ?></label>
							<input class="form-control" name="login" value="<?= $vars['values']['login'];?>" autofocus/>
						</div>
						<div class="form-group">
							<label><?= __('Password') ?></label>
							<input type="password" class="form-control" name="password" value=""/>
						</div>
						<div class="form-group">
							<input type="submit" class="btn btn-success" value="<?= __('Sign in') ?>"/>
						</div>
					</form>
				</div>

				<div class="panel-heading">
					<h3 class="panel-title">
						<?= __('Sign in with social network') ?>
					</h3>
				</div>
				<div class="panel-body">
					<div class="social-network-auth">
						<a href="/user/socialAuth?provider=vk"><i class="fa fa-vk"></i></a>
						<a href="/user/socialAuth?provider=twitter"><i class="fa fa-twitter"></i></a>
						<a href="/user/socialAuth?provider=facebook"><i class="fa fa-facebook"></i></a>
						<a href="/user/socialAuth?provider=google"><i class="fa fa-google"></i></a>
					</div>
				</div>
			</div>
		</div>
		<div class="col-sm-6">
			<div class="panel panel-smart">
				<div class="panel-heading">
					<h3 class="panel-title">
						<?= __('Create new account'); ?>
					</h3>
				</div>
				<div class="panel-body">
					<p>
						<?= __('Registration allows you to avoid filling in billing and shipping forms every time you checkout on this website'); ?>
					</p>
					<a href="/user/register" class="btn btn-brown text-uppercase">
						<?= __('Register'); ?>
					</a>
				</div>
			</div>

		</div>
	</div>
</section>
