<div class="row">
	<div class="col-lg-12">
		<?php echo $vars['breadcrumbs']; ?>
	</div>
</div>

<h2 class="sub-heading text-center">
	<?= __('Orders') ?>
</h2>

<div class="row">
	<div class="col-lg-12">
		<ul class="nav nav-pills">
			<li role="presentation"><a href="/user"><?= __('Profile') ?></a></li>
			<li role="presentation" class="active"><a href="/order"><?= __('Orders') ?></a></li>
			<li role="presentation"><a href="/user/social_networks"><?= __('Social Networks') ?></a></li>
		</ul>
	</div>
</div>

<br/>

<div class="container-fluid">
	<div class="row">
		<div class="table-responsive shopping-cart-table">
			<table class="table table-bordered">
				<thead>
				<tr>
					<th>#</th>
					<th><?= __('Date') ?></th>
					<th><?= __('Sum') ?></th>
					<th><?= __('Status') ?></th>
					<th><?= __('Actions') ?></th>
				</tr>
				</thead>
				<tbody>
				<?php $counter = 1; ?>
				<?php foreach ($vars['orders'] as $item) { ?>
					<tr>
						<td><?= $item['id']; ?></td>
						<td><?= $item['date']; ?></td>
						<td><?= \App\Service\Product::viewPrice($item['sum']); ?></td>
						<td><?= $item['status_text']; ?></td>
						<td><a href="/order/show/<?= $item['id']; ?>"><?= __('details'); ?></a></td>
					</tr>
				<?php } ?>
				</tbody>
			</table>
		</div>
	</div>
</div>