<div class="row">
	<div class="col-lg-12">
		<?php echo $vars['breadcrumbs']; ?>
	</div>
</div>

<h2 class="sub-heading text-center">
	<?= __('Order details') ?> #<?=$vars['order']['id'];?>
</h2>

<div class="row" xmlns="http://www.w3.org/1999/html">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Products') ?></h3>
	</div>
</div>

<div class="table-responsive shopping-cart-table">
	<form type="post" action="/cart/recalculate">
		<table class="table table-bordered">
			<thead>
			<tr>
				<td>#</td>
				<td class="text-center"><?= __('Photo') ?></td>
				<td class="text-center"><?= __('Name') ?></td>
				<td class="text-center"><?= __('Count') ?></td>
				<td class="text-center"><?= __('Price') ?></td>
				<td class="text-center"><?= __('Sum') ?></td>
			</tr>
			</thead>
			<tbody>
			<?php $counter = 1; ?>
			<?php foreach ($vars['products'] as $item) { ?>
				<tr>
					<td><?= $counter++; ?></td>
					<td class="text-center"><img height="100" src="/api.php?method=Resource.get&id=<?= $item['photo_id']; ?>" /></td>
					<td class="text-center"><a href="/product/view/<?=$item['url'];?>"><?= $item['name']; ?></a></td>
					<td class="text-center"><?= $item['count']; ?></td>
					<td class="text-center"><?= \App\Service\Product::viewPrice($item['price'], 2); ?></td>
					<td class="text-center"><?= \App\Service\Product::viewPrice($item['price'] * $item['count'], 2); ?></td>
				</tr>
			<?php } ?>
			<tr>
				<td colspan="5" class="text-right">
					<strong><?= __('Total'); ?> :</strong>
				</td>
				<td><strong><?= \App\Service\Product::viewPrice($vars['order']['sum'], 2); ?></strong></td>
			</tr>
			</tbody>
		</table>
	</form>
</div>

<div class="row" xmlns="http://www.w3.org/1999/html">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Order details') ?></h3>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
			<input type="hidden" name="id" value="<?= $vars['order']['id']; ?>"/>
			<div class="form-group">
				<label><?= __('Sum') ?></label>
				<input class="form-control" name="login" value="<?= $vars['order']['sum']; ?>" readonly />
			</div>
			<div class="form-group">
				<label><?= __('First name') ?></label>
				<input class="form-control" name="info[firstName]"
					   value="<?= $vars['order']['firstName']; ?>" readonly />
			</div>
			<div class="form-group">
				<label><?= __('Last name') ?></label>
				<input class="form-control" name="info[lastName]"
					   value="<?= $vars['order']['lastName']; ?>" readonly />
			</div>
			<div class="form-group">
				<label><?= __('Phone') ?></label>
				<input class="form-control" name="info[phone]" value="<?= $vars['order']['phone']; ?>" readonly/>
			</div>
			<div class="form-group">
				<label><?= __('Address') ?></label>
				<input class="form-control" name="info[address]" value="<?= $vars['order']['address']; ?>" readonly/>
			</div>
			<div class="form-group">
				<label><?= __('Comment') ?></label>
				<textarea class="form-control" name="comment" readonly><?= $vars['order']['comment']; ?></textarea>
			</div>
	</div>
</div>
