<div class="row">
	<div class="col-lg-12">
		<?php echo $vars['breadcrumbs']; ?>
	</div>
</div>

<h2 class="main-heading text-center">
	<?= __('Register') ?>
</h2>

<?php echo $this->getNotices(); ?>


<section class="registration-area">
	<div class="row">
		<div class="col-sm-6">
			<form role="form" method="post" action="/user/register" autocomplete="off">
				<div class="panel panel-smart">
					<div class="panel-heading">
						<h3 class="panel-title"><?= __('User Information'); ?></h3>
					</div>
					<div class="panel-body">
						<div class="form-group">
							<label><?= __('Login') ?></label>
							<input class="form-control" name="login" value=""/>
						</div>
						<div class="form-group">
							<label><?= __('E-Mail') ?></label>
							<input class="form-control" name="info[email]" value=""/>
						</div>
						<div class="form-group">
							<label><?= __('First name') ?></label>
							<input class="form-control" name="info[firstName]" value=""/>
						</div>
						<div class="form-group">
							<label><?= __('Last name') ?></label>
							<input class="form-control" name="info[lastName]" value=""/>
						</div>
						<div class="form-group">
							<label><?= __('Phone') ?></label>
							<input class="form-control" name="info[phone]" value=""/>
						</div>
						<div class="form-group">
							<label><?= __('Address') ?></label>
							<input class="form-control" name="info[address]" value=""/>
						</div>
					</div>

					<div class="panel-heading">
						<h3 class="panel-title"><?= __('Password'); ?></h3>
					</div>
					<div class="panel-body">
						<div class="form-group">
							<label><?= __('Password') ?></label>
							<input class="form-control" name="password" value=""/>
						</div>

						<div class="form-group">
							<label><?= __('Password repeat') ?></label>
							<input class="form-control" name="password_repeat" value=""/>
						</div>

						<div class="form-group">
							<input name="register" type="submit" class="btn btn-success" value="<?= __('Register') ?>"/>
						</div>
					</div>
				</div>
			</form>
		</div>
		<div class="col-sm-6">
			<div class="panel panel-smart">
				<div class="panel-heading">
					<h3 class="panel-title">
						<?= __('Registration'); ?>
					</h3>
				</div>
				<div class="panel-body">
					<?= htmlspecialchars_decode($vars['text']); ?>
				</div>
			</div>
		</div>
	</div>
</section>