<form role="form" action="/admin/meta/update">
	<input type="hidden" name="moduleId" value="<?= $vars['moduleId']; ?>"/>
	<input type="hidden" name="url" value="<?= $vars['url']; ?>"/>
	<div class="form-group">
		<label>Title</label>
		<input class="form-control" name="title" value="<?= $vars['meta']['title']; ?>"/>
	</div>
	<div class="form-group">
		<label>Keywords</label>
		<input class="form-control" name="keywords" value="<?= $vars['meta']['keywords']; ?>"/>
	</div>
	<div class="form-group">
		<label>Description</label>
		<input class="form-control" name="description" value="<?= $vars['meta']['description']; ?>"/>
	</div>
	<div class="form-group">
		<input type="submit" class="btn btn-default" value="<?= __('Save') ?>"/>
		<input type="button" class="btn btn-cancel" onclick="location.href='/admin/<?= $vars['module'];?>';" value="<?= __('Cancel') ?>"/>
	</div>
</form>