<div class="row">
	<div class="col-lg-12">
		<div class="dataTables_info">
			<?= __('Showing') ?>
			<?=$this->paging->firstItemOnPage();?> - <?=$this->paging->lastItemOnPage();?>
			<?= __('of') ?> <?=$vars['total'];?> <?= __('entries') ?>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="dataTables_paginate paging_simple_numbers" id="dataTables-example_paginate">
			<ul class="pagination">

				<?php if ($this->paging->needsPaging()) { ?>

					<?php if (!$this->paging->isFirstPage()) { ?>

						<li class="paginate_button previous" aria-controls="dataTables-example" tabindex="0" id="dataTables-example_previous">
							<a href="?page=<?=$vars['previous'];?>">
								<?= __('Previous page') ?>
							</a>
						</li>

					<?php } ?>

					<?php for ($page = 1; ($page-1) * $vars['onpage'] < $vars['total']; $page++) { ?>

						<?php $active = ($page == $vars['page']) ? 'active' : ''; ?>

						<li class="paginate_button <?=$active;?>" aria-controls="dataTables-example" tabindex="0">
							<a href="?page=<?=$page;?>">
								<?=$page;?>
							</a>
						</li>

					<?php } ?>

					<?php if (!$this->paging->isLastPage()) { ?>

						<li class="paginate_button next" aria-controls="dataTables-example" tabindex="0" id="dataTables-example_next">
							<a href="?page=<?=$vars['next'];?>">
								<?= __('Next page') ?>
							</a>
						</li>

					<?php } ?>

				<?php } ?>

			</ul>
		</div>
	</div>
</div>