<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Add new currency') ?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/currency/save">
			<div class="form-group">
				<label><?= __('Symbol') ?></label>
				<input class="form-control" name="symbol" value=""/>
			</div>
			<div class="form-group">
				<label><?= __('Symbol position') ?></label>
				<select class="form-control" name="position">
					<option value="1"><?= __('Left');?></option>
					<option value="2"><?= __('Right');?></option>
				</select>
			</div>
			<div class="form-group">
				<label><?= __('Name') ?></label>
				<input class="form-control" name="name" value=""/>
			</div>
			<div class="form-group">
				<label><?= __('Rate') ?></label>
				<input class="form-control" name="rate" value=""/>
			</div>
			<div class="form-group">
				<label><?= __('Basic') ?></label>
				<input type="checkbox" class="form-control" name="basic" value=""/>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="<?= __('Save') ?>"/>
				<input type="button" class="btn btn-primary" onclick="location.href='/admin/currency';" value="<?= __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>
