<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"><?= __('Currency') ?></h1>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<button class="btn btn-primary"
				onclick="location.href='/admin/currency/new'"><?= __('Add new currency') ?></button>
	</div>
</div>

<br/>
<div class="dataTable_wrapper">
	<div class="dataTables_wrapper">
		<div class="row">
			<div class="col-lg-12">
				<table class="table table-bordered dataTable">
					<thead>
					<tr>
						<th>ID</th>
						<th><?= __('Symbol') ?></th>
						<th><?= __('Name') ?></th>
						<th><?= __('Rate') ?></th>
						<th><?= __('Basic') ?></th>
						<th><?= __('Actions') ?></th>
					</tr>
					</thead>
					<tbody>
					<?php
					foreach ($vars['currencies'] as $row) {
						echo '
                        <tr>
                            <td>' . $row['id'] . '</td>
                            <td>' . $row['symbol'] . '</td>
                            <td>' . $row['name'] . '</td>
                            <td>' . $row['rate'] . '</td>
                            <td>' . ($row['basic'] ? __('Yes') : __('No')) . '</td>
                            <td>' . _snippet('actions', [$row['id'], 'currency', ['duplicate', 'delete']]) . '</td>
                        </tr>';
					}
					?>
					</tbody>
				</table>
			</div>
		</div>
		<?php echo $vars['paging']; ?>
	</div>
</div>
