<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><? __('Add new mail template') ?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/mail_template/save">
			<div class="form-group">
				<label><? __('Subject') ?></label>
				<input class="form-control" name="subject" value=""/>
			</div>
			<div class="form-group">
				<label><? __('Alias') ?></label>
				<input class="form-control" name="alias" value=""/>
			</div>
			<div class="form-group">
				<label><? __('Body') ?></label>
				<textarea rows="20" id="editor-1" class="form-control" name="body"></textarea>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="<? __('Save') ?>"/>
				<input type="button" class="btn btn-primary" onclick="location.href='/admin/mail_template';" value="<? __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>

<script>
	CodeMirror.fromTextArea(document.getElementById("editor-1"), {
		lineNumbers: true,
		mode: { name: "htmlmixed" }
	});
</script>