<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Edit template') ?> - <?=$vars['template']['subject'];?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/mail_template/save">
			<input type="hidden" name="id" value="<?= $vars['template']['id']; ?>"/>
			<div class="form-group">
				<label><?= __('Subject') ?></label>
				<input class="form-control" name="subject" value="<?= $vars['template']['subject']; ?>"/>
			</div>
			<div class="form-group">
				<label><?= __('Alias') ?></label>
				<input class="form-control" name="alias" value="<?= $vars['template']['alias']; ?>"/>
			</div>
			<div class="form-group">
				<label><?= __('Body') ?></label>
				<textarea id="editor" rows="20" class="form-control" name="body"><?= $vars['template']['body']; ?></textarea>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-default" value="<?= __('Save') ?>"/>
				<input type="button" class="btn btn-cancel" onclick="location.href='/admin/mail_template';" value="<?= __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>

<script>
	CodeMirror.fromTextArea(document.getElementById("editor"), {
		lineNumbers: true,
		mode: { name: "htmlmixed" }
	});
</script>