<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"><? __('Mail Templates') ?></h1>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<button class="btn btn-primary" onclick="location.href='/admin/mail_template/new'"><? __('Add new mail template') ?></button>
	</div>
</div>

<br/>
<div class="dataTable_wrapper">
	<div class="dataTables_wrapper">
		<div class="row">
			<div class="col-lg-12">
				<table class="table table-bordered dataTable">
					<thead>
					<tr>
						<th>ID</th>
						<th><? __('Name') ?></th>
						<th><? __('Alias') ?></th>
						<th><? __('Active') ?></th>
						<th><? __('Actions') ?></th>
					</tr>
					</thead>
					<tbody>
					<?php
					foreach ($vars['templates'] as $row) {
						echo '
                        <tr>
                            <td>' . $row['id'] . '</td>
                            <td>' . $row['subject'] . '</td>
                            <td>' . $row['alias'] . '</td>
                            <td>' . _snippet('active', [$row['id'], 'mail_template', $row['active']]) . '</td>
                            <td>' . _snippet('actions', [$row['id'], 'mail_template', ['duplicate', 'delete']]) . '</td>
                        </tr>';
					}
					?>
					</tbody>
				</table>
			</div>
		</div>
		<?php echo $vars['paging']; ?>
	</div>
</div>
