<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><? __('Edit setting') ?> - <?=$vars['catalog']['name'];?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/setting/save">
			<input type="hidden" name="id" value="<?= $vars['setting']['id']; ?>"/>
			<div class="form-group">
				<label><? __('Key') ?></label>
				<input class="form-control" name="key" value="<?= $vars['setting']['key']; ?>"/>
			</div>
			<div class="form-group">
				<label><? __('Value') ?></label>
				<input class="form-control" name="value" value="<?= $vars['setting']['value']; ?>"/>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="<? __('Save') ?>"/>
				<input type="button" class="btn btn-primary" onclick="location.href='/admin/setting';" value="<? __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>

