<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Edit infoblock') ?> - <?=$vars['page']['name'];?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/infoblock/save">
			<input type="hidden" name="id" value="<?= $vars['page']['id']; ?>"/>
			<div class="form-group">
				<label><?= __('Name') ?></label>
				<input class="form-control" name="name" value="<?= $vars['page']['name']; ?>"/>
			</div>
			<div class="form-group">
				<label><?= __('Alias') ?></label>
				<input class="form-control" name="alias" value="<?= $vars['page']['alias']; ?>"/>
			</div>
			<div class="form-group">
				<label><?= __('Text') ?></label>
				<textarea id="editor-1" class="form-control" name="text"><?= $vars['page']['text']; ?></textarea>
				<script>CKEDITOR.replace('editor-1');</script>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-default" value="<?= __('Save') ?>"/>
				<input type="button" class="btn btn-cancel" onclick="location.href='/admin/infoblock';" value="<?= __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>
