<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Add new filter set') ?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/filter/save">
			<div class="form-group">
				<label><?= __('Name') ?></label>
				<input class="form-control" name="name" value=""/>
			</div>
			<div class="form-group">
				<label><?= __('Alias') ?></label>
				<input class="form-control" name="alias" value=""/>
			</div>
			<div class="form-group">
				<label><?= __('Description') ?></label>
				<textarea id="editor-1" class="form-control" name="info"></textarea>
				<script>CKEDITOR.replace('editor-1');</script>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="<?= __('Save') ?>"/>
				<input type="button" class="btn btn-primary" onclick="location.href='/admin/filter';" value="<?= __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>
