<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><? __('Edit filter set') ?> - <?=$vars['filter']['name'];?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
	<li role="presentation" class="active"><a href="#info" aria-controls="info" role="tab" data-toggle="tab"><? __('Information') ;?></a></li>
	<li role="presentation"><a href="#filters" aria-controls="filters" role="tab" data-toggle="tab"><? __('Filters') ;?></a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
	<div role="tabpanel" class="tab-pane active" id="info">

		<div class="row">
			<div class="col-lg-12">
				<form role="form" action="/admin/filter/save">
					<input type="hidden" name="id" value="<?= $vars['catalog']['id']; ?>"/>
					<div class="form-group">
						<label><? __('Name') ?></label>
						<input class="form-control" name="name" value="<?= $vars['filter']['name']; ?>"/>
					</div>
					<div class="form-group">
						<label><? __('Alias') ?></label>
						<input class="form-control" name="url" value="<?= $vars['filter']['alias']; ?>"/>
					</div>
					<div class="form-group">
						<label><? __('Text') ?></label>
						<textarea id="editor-1" class="form-control" name="info"><?= $vars['filter']['info']; ?></textarea>
						<script>CKEDITOR.replace('editor-1');</script>
					</div>
					<div class="form-group">
						<input type="submit" class="btn btn-success" value="<? __('Save') ?>"/>
						<input type="button" class="btn btn-primary" onclick="location.href='/admin/filter';" value="<? __('Cancel') ?>"/>
					</div>
				</form>
			</div>
		</div>
	</div>
	<div role="tabpanel" class="tab-pane active" id="filters">
	</div>
</div>
