		<div class="row">
			<div class="col-lg-6">
				<div class="dataTables_info" id="dataTables-example_info" role="status" aria-live="polite">Showing <?=$vars['offset'];?> to
					<?=$vars['items'] + $vars['onpage'] * ($vars['page'] - 1);?> of <?=$vars['total'];?> entries
				</div>
			</div>
			<div class="col-lg-6">
				<div class="dataTables_paginate paging_simple_numbers" id="dataTables-example_paginate">
					<ul class="pagination">

						<?php
							if ($vars['total'] > $vars['items']) {

								if ($vars['page'] > 1) echo '<li class="paginate_button previous" aria-controls="dataTables-example" tabindex="0"
						    id="dataTables-example_previous"><a href="?page='.($vars['page'] - 1).'">Previous</a></li>';

							for ($page = 1; ($page-1) * $vars['onpage'] < $vars['total']; $page++) {
						?>

							<li class="paginate_button " aria-controls="dataTables-example" tabindex="0"><a href="?page=<?=$page;?>">
									<?=$page;?>
								</a>
							</li>

						<?php }

							if ($vars['page']*$vars['onpage'] < $vars['total']) echo '<li class="paginate_button next" aria-controls="dataTables-example" tabindex="0"
						    id="dataTables-example_next"><a href="?page='.($vars['page']+1).'">Next</a></li>';

							} ?>

					</ul>
				</div>
			</div>
		</div>