<div class="row">
	<div class="col-lg-6">
		<div class="dataTables_info">
			Showing 
			<?=$this->paging->firstItemOnPage();?> to <?=$this->paging->lastItemOnPage();?> 
			of <?=$vars['total'];?> entries
		</div>
	</div>
	<div class="col-lg-6">
		<div class="dataTables_paginate paging_simple_numbers" id="dataTables-example_paginate">
			<ul class="pagination">

				<?php if ($this->paging->needsPaging()) { ?>

					<?php if (!$this->paging->isFirstPage()) { ?>

						<li class="paginate_button previous" aria-controls="dataTables-example" tabindex="0" id="dataTables-example_previous">
							<a href="?page=<?=$vars['previous'];?>">
								Previous
							</a>
						</li>

					<?php } ?>

					<?php for ($page = 1; ($page-1) * $vars['onpage'] < $vars['total']; $page++) { ?>

						<li class="paginate_button " aria-controls="dataTables-example" tabindex="0">
							<a href="?page=<?=$page;?>">
								<?=$page;?>
							</a>
						</li>

					<?php } ?>

					<?php if (!$this->paging->isLastPage()) { ?>

						<li class="paginate_button next" aria-controls="dataTables-example" tabindex="0" id="dataTables-example_next">
							<a href="?page=<?=$vars['next'];?>">
								Next
							</a>
						</li>

					<?php } ?>

				<?php } ?>

			</ul>
		</div>
	</div>
</div>