<div class="row">
	<div class="col-lg-12">
		<?php echo $vars['breadcrumbs']; ?>
	</div>
</div>

<div class="row">
	<div class="col-md-9">
		<h2 class="main-heading2"><?= $vars['catalog']['name']; ?></h2>

		<?php include 'products_sort.phtml'; ?>

		<div id="products-list">
			<?php include 'products.phtml'; ?>
		</div>

		<div id="paging">
			<?php include 'paging.phtml'; ?>
		</div>
	</div>

	<div class="col-md-3">
		<h3 class="side-heading"><?= __('All categories') ?></h3>
		<?php include 'catalogs_list.phtml'; ?>

		<?php if ($vars['filters']) { ?>
			<h3 class="side-heading"><?= __('Filter') ?></h3>
			<?php include 'products_filters.phtml'; ?>
		<?php } ?>
	</div>
</div>

<script>
	$('#products-filters').on('click', function (e) {
		if ($(e.target).hasClass('filter')) {

			$('#paging li').removeClass('active');
			$('#paging li').first().addClass('active');

			requestProducts(<?=$vars['catalogId']?>, '<?=json_encode($vars['args']);?>');
		}
	});

	$('#products-sort').on('change', function () {
		requestProducts(<?=$vars['catalogId']?>, '<?=json_encode($vars['args']);?>');
	});

	$('#paging').on('click', function (e) {
		$('#paging li').removeClass('active');
		$(e.target).parent().addClass('active');
		requestProducts(<?=$vars['catalogId']?>, '<?=json_encode($vars['args']);?>');
		e.preventDefault();
		return false;
	});
</script>
