<div class="row">
	<div class="col-lg-12">
		<?php echo $vars['breadcrumbs']; ?>
	</div>
</div>

<div class="row">
	<div class="col-md-9">
		<h2 class="main-heading2"><?= $vars['catalog']['name']; ?></h2>
		<div class="row cat-intro">
			<div class="col-sm-3">
				<img src="/api.php?method=Resource.get&id=<?=$vars['catalog']['photo_id'];?>" alt="Image"
					 class="img-responsive img-thumbnail"/>
			</div>
			<div class="col-sm-9 cat-body">
				<?= htmlspecialchars_decode($vars['catalog']['text']); ?>
			</div>
		</div>

		<?php include 'products_sort.phtml'; ?>

		<div id="products-list">
			<?php include 'products.phtml'; ?>
		</div>
	</div>

	<div class="col-md-3">
		<h3 class="side-heading"><?= __('All categories') ?></h3>
		<?php include 'catalogs_list.phtml'; ?>

		<h3 class="side-heading"><?= __('Filter') ?></h3>
		<?php include 'products_filters.phtml'; ?>
	</div>
</div>

<script>
	$('#products-filters').on('click', function (e) {
		if ($(e.target).hasClass('filter')) {
			requestProducts(<?=$vars['catalogId']?>, '<?=json_encode($vars['args']);?>');
		}
	});

	$('#products-sort').on('change', function () {
		requestProducts(<?=$vars['catalogId']?>, '<?=json_encode($vars['args']);?>');
	});
</script>
