<div class="col-xs-12">
	<div class="product-col list clearfix">
		<div class="image">
			<a href="/product/view/<?= $product['url']; ?>">
				<img src="/api.php?method=Resource.get&id=<?=$product['photo_id'];?>" alt="product" class="img-responsive" />
			</a>
		</div>
		<div class="caption">
			<h4><a href="/product/view/<?= $product['url']; ?>"><?= $product['name']; ?></a></h4>
			<div class="description">
				<?= $product['text_m']; ?>
			</div>
			<div class="price">
				<?php if ($product['old_price'] > 0) { ?>
				<span class="price-old"><?= \App\Service\Product::viewPrice($product['old_price']); ?></span>
				<?php } ?>
				<span class="price-new"><?= \App\Service\Product::viewPrice($product['price']); ?></span>
			</div>

			<div class="cart-button button-group">
				<a type="button" class="btn btn-cart" href="/product/view/<?= $product['url']; ?>">
					<?= __('Details'); ?>
				</a>
			</div>

		</div>
	</div>
</div>