<div class="list-group" id="products-filters">
		<?php
			foreach ($vars['filters'] as $cat) {
				echo '<div class="list-group-item">' . $cat['name'] . '</div>';
				echo '<div class="list-group-item"><div class="filter-group">';

				foreach ($cat['filters'] as $filter) {
					$checked = in_array($filter['id'], $vars['checked_filters']) ? 'checked' : '';
					$disabled = ($filter['count'] == 0) ? 'disabled' : '';

					echo '<label ' . ($disabled ? 'style="opacity:0.5;"' : '') . ' class="checkbox"><input type="checkbox" ' . $checked . ' ' . $disabled . ' class="filter" value="' . $filter['id'] . '" name="filter[]"  />&nbsp;&nbsp;';
					echo $filter['name'] . ' (' . $filter['count'] . ')</label>';
				}
				echo '</div></div>';
			}
		?>
</div>