<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"><?= __('Feedback messages') ?></h1>
	</div>
</div>

<br/>

<div class="dataTable_wrapper">
	<div class="dataTables_wrapper">
		<div class="row">
			<div class="col-lg-12">
				<table class="table table-bordered dataTable">
					<thead>
					<tr>
						<th>ID</th>
						<th><?= __('Date') ?></th>
						<th><?= __('Name') ?></th>
						<th><?= __('Subject') ?></th>
						<th><?= __('Actions') ?></th>
					</tr>
					</thead>
					<tbody>
					<?php
					foreach ($vars['messages'] as $row) {
						echo '
                        <tr>
                            <td>' . $row['id'] . '</td>
                            <td>' . $row['date'] . '</td>
                            <td>' . $row['name'] . '</td>
                            <td>' . $row['subject'] . '</td>
                            <td>' . _snippet('actions', [$row['id'], 'feedback', ['delete']]) . '</td>
                        </tr>';
					}
					?>
					</tbody>
				</table>
			</div>
		</div>
		<?php echo $vars['paging']; ?>
	</div>
</div>
