<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<title><?= __('Admin Dashboard'); ?></title>
	<link rel="icon" href="/public/admin/favicon.ico" />

	<?php echo $this->loadResources('css'); ?>
	<?php echo $this->loadResources('js'); ?>

</head>

<body>
<div id="wrapper">
	<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
		<?php echo $this->load('phtml', '/templates/topbar.phtml', $vars); ?>
		<?php echo $this->load('phtml', '/templates/sidebar.phtml', $vars); ?>
	</nav>
	<div id="page-wrapper">
		<?php echo $vars['content']; ?>
	</div>
</div>
</body>
</html>
