<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"><?= __('Dashboard'); ?></h1>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<h4><?= __('Web Site'); ?></h4>
		<?php foreach ($vars['modules']['site'] as $module) include 'index_module_tile.phtml'; ?>
	</div>
</div>

<hr/>

<div class="row">
	<div class="col-lg-12">
		<h4><?= __('Online Shop'); ?></h4>
		<?php foreach ($vars['modules']['shop'] as $module) include 'index_module_tile.phtml'; ?>
	</div>
</div>

<hr/>

<div class="row">
	<div class="col-lg-12">
		<h4><?= __('Administration'); ?></h4>
		<?php foreach ($vars['modules']['admin'] as $module) include 'index_module_tile.phtml'; ?>
	</div>
</div>

<hr/>

<div class="row">
	<div class="col-lg-12">
		<h4><?= __('SEO'); ?></h4>
		<?php foreach ($vars['modules']['seo'] as $module) include 'index_module_tile.phtml'; ?>
	</div>
</div>

<hr/>
