<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Admin Dashboard</title>
	<?php echo $this->loadResources('css'); ?>
</head>
<body>
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			<div class="login-panel panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Please Sign In</h3>
				</div>
				<div class="panel-body">
					<form role="form" method="post" action="login">
						<fieldset>
							<div class="form-group">
								<input class="form-control" placeholder="E-mail" name="login" type="text" autofocus>
							</div>
							<div class="form-group">
								<input class="form-control" placeholder="Password" name="password" type="password"
									   value="">
							</div>
							<div class="checkbox">
								<label>
									<input name="remember" type="checkbox" value="Remember Me"><?= __('Remember Me') ?>
								</label>
							</div>

							<?php echo $this->getNotices(); ?>

							<button type="submit" class="btn btn-lg btn-success btn-block"> <?= __('Login') ?></button>
						</fieldset>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<?php echo $this->loadResources('js'); ?>

</body>
</html>
