<div class="navbar-default sidebar" role="navigation">
	<div class="sidebar-nav navbar-collapse">
		<ul class="nav" id="side-menu">
			<li>
				<a href="/admin/"><i class="fa fa-dashboard fa-fw"></i> <? __('Dashboard') ?></a>
			</li>
			<li>
				<a href="/admin/menu"><i class="fa fa-th-list fa-fw"></i> <? __('Menu') ?></a>
			</li>
			<li>
				<a href="/admin/page"><i class="fa fa-th fa-fw"></i> <? __('Pages') ?></a>
			</li>
			<li>
				<a href="/admin/admin"><i class="fa fa-exclamation-circle fa-fw"></i> <? __('Administrators') ?></a>
			</li>
			<li>
				<a href="/admin/catalog"><i class="fa fa-folder-open fa-fw"></i> <? __('Catalog') ?></a>
			</li>
			<li>
				<a href="/admin/product"><i class="fa fa-edit fa-fw"></i> <? __('Product') ?></a>
			</li>
			<li>
				<a href="/admin/database"><i class="fa fa-database fa-fw"></i> <? __('Database') ?></a>
			</li>
			<li>
				<a href="/admin/translation"><i class="fa fa-language fa-fw"></i> <? __('Translation') ?></a>
			</li>
		</ul>
	</div>
</div>
