<div class="navbar-header">
	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	</button>
	<a class="navbar-brand" href="#">Admin Dashboard</a>
</div>

<ul class="nav navbar-top-links navbar-right">
	<li class="dropdown">
		<a class="dropdown-toggle" data-toggle="dropdown" href="#">
			<?= strtoupper(\Core\Config::get('site.language')); ?> <i class="fa fa-caret-down"></i>
		</a>
		<ul class="dropdown-menu dropdown-lang">
			<li>
				<a href="/admin/lang?switch=ru">
					<div>Русский</div>
				</a>
			</li>
			<li class="divider"></li>
			<li>
				<a href="/admin/lang?switch=en">
					<div>English</div>
				</a>
			</li>
		</ul>
	</li>

	<li class="dropdown">
		<a class="dropdown-toggle" data-toggle="dropdown" href="#">
			<i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
		</a>
		<ul class="dropdown-menu dropdown-user">
			<li><a href="/admin/logout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
			</li>
		</ul>
	</li>
</ul>
