<div class="navbar-header">
	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	</button>
	<a class="navbar-brand" href="/admin/"><?= __('Dashboard') ?></a>
	<a class="navbar-brand" title="<?= __('go to site') ?>" href="/" target="_blank"><i class="fa fa-share-square"></i></a>
</div>

<ul class="nav navbar-top-links navbar-right">
	<li class="dropdown">
		<a class="dropdown-toggle" data-toggle="dropdown" href="#">
			<?= strtoupper(\Core\Config::get('site.language')); ?> <i class="fa fa-caret-down"></i>
		</a>
		<ul class="dropdown-menu dropdown-lang">
			<?php foreach ($vars['languages'] as $key => $lang) { ?>
				<li>
					<a href="/admin/lang?switch=<?= $key; ?>"><?= $lang; ?></a>
				</li>
			<?php } ?>
		</ul>
	</li>

	<li class="dropdown">
		<a class="dropdown-toggle" data-toggle="dropdown" href="#">
			<i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
		</a>
		<ul class="dropdown-menu dropdown-user">
			<?php if ($vars['user']) { ?>
				<li><a><i class="fa fa-user fa-fw"></i> <?=$vars['user']->getValue('name');?></a>
				</li>
			<?php } ?>
			<li class="divider"></li>
			<li><a href="/admin/logout"><i class="fa fa-sign-out fa-fw"></i> <?= __('Logout') ?></a>
			</li>
		</ul>
	</li>
</ul>
