<div class="navbar-header">
	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	</button>
	<a class="navbar-brand" href="/admin/"><? __('Dashboard') ?></a>
</div>

<ul class="nav navbar-top-links navbar-right">
	<li class="dropdown">
		<a class="dropdown-toggle" data-toggle="dropdown" href="#">
			<?= strtoupper(\Core\Config::get('site.language')); ?> <i class="fa fa-caret-down"></i>
		</a>
		<ul class="dropdown-menu dropdown-lang">
			<?php foreach ($vars['languages'] as $key => $lang) { ?>
				<li>
					<a href="/admin/lang?switch=<?= $key; ?>"><?= $lang; ?></a>
				</li>
			<?php } ?>
		</ul>
	</li>

	<li class="dropdown">
		<a class="dropdown-toggle" data-toggle="dropdown" href="#">
			<i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
		</a>
		<ul class="dropdown-menu dropdown-user">
			<?php if ($vars['user']) { ?>
				<li><a href="/admin/admin/edit/<?php echo $vars['user']->getId(); ?>"><i class="fa fa-user fa-fw"></i> <? __('User Profile'); ?></a>
				</li>
			<?php } ?>
			<li><a href="#"><i class="fa fa-gear fa-fw"></i> <? __('Settings'); ?></a>
			</li>
			<li class="divider"></li>
			<li><a href="/admin/logout"><i class="fa fa-sign-out fa-fw"></i> <? __('Logout') ?></a>
			</li>
		</ul>
	</li>
</ul>
