<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><? __('Add new administrator') ?></h3>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/admin/save">
			<div class="form-group">
				<label><? __('Name') ?></label>
				<input class="form-control" name="name" value=""/>
			</div>
			<div class="form-group">
				<label><? __('Login') ?></label>
				<input class="form-control" name="url" value=""/>
			</div>
			<div class="form-group">
				<label><? __('Password') ?></label>
				<input class="form-control" name="password" value=""/>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="<? __('Save') ?>"/>
				<input type="button" class="btn btn-primary" onclick="location.href='/admin/admin';" value="<? __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>
