<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Edit administrator') ?> - <?=$vars['admin']['name'];?></h3>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/admin/save">
			<input type="hidden" name="id" value="<?= $vars['admin']['id']; ?>"/>
			<div class="form-group">
				<label><?= __('Name') ?></label>
				<input class="form-control" name="name" value="<?= $vars['admin']['name']; ?>"/>
			</div>
			<div class="form-group">
				<label><?= __('Login') ?></label>
				<input class="form-control" name="login" value="<?= $vars['admin']['login']; ?>"/>
			</div>
			<div class="form-group">
				<label><?= __('Group') ?></label>
				<select class="form-control" name="groupId">
					<?php
					foreach ($vars['groups'] as $id => $name) {
						$selected = ($vars['admin']['groupId'] == $id) ? 'selected' : '';
						echo '<option ' . $selected . ' value="' . $id . '">' . $name . '</option>';
					}
					?>
				</select>
			</div>
			<div class="form-group">
				<label><?= __('Password') ?></label>
				<input class="form-control" name="password" value=""/>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="<?= __('Save') ?>"/>
				<input type="button" class="btn btn-primary" onclick="location.href='/admin/admin';" value="<?= __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>
