<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"><? __('Administrators') ?></h1>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<button class="btn btn-primary" onclick="location.href='/admin/admin/new'"><? __('Add new admin') ?></button>
	</div>
</div>

<br/>
<div class="dataTable_wrapper">
	<div class="dataTables_wrapper">
		<div class="row">
			<div class="col-lg-12">
				<table class="table table-bordered dataTable">
					<thead>
					<tr>
						<th>ID</th>
						<th><? __('Login') ?></th>
						<th><? __('Group') ?></th>
						<th><? __('Active') ?></th>
						<th><? __('Actions') ?></th>
					</tr>
					</thead>
					<tbody>
					<?php
					foreach ($vars['admins'] as $row) {
						echo '
                        <tr>
                            <td>' . $row->id . '</td>
                            <td>' . $row->login . '</td>
                            <td>' . $row->getRelatedValue('admin_group.name') . '</td>
                            <td>' . _snippet('active', [$row->id, 'admin', $row->active]) . '</td>
                            <td>' . _snippet('actions', [$row->id, 'admin', ['duplicate', 'delete']]) . '</td>
                        </tr>';
					}
					?>
					</tbody>
				</table>
			</div>
		</div>
		<?php echo $vars['paging']; ?>
	</div>
</div>