<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><? __('Add group') ?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/admin_group/save">
			<div class="form-group">
				<label><? __('Name') ?></label>
				<input class="form-control" name="name" value=""/>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="<? __('Save') ?>"/>
				<input type="button" class="btn btn-primary" onclick="location.href='/admin/admin_group';" value="<? __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>
