<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><? __('Edit group') ?> - <?=$vars['group']['name'];?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/admin_group/save">
			<input type="hidden" name="id" value="<?= $vars['group']['id']; ?>"/>
			<div class="form-group">
				<label><? __('Name') ?></label>
				<input class="form-control" name="name" value="<?= $vars['group']['name']; ?>"/>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-default" value="<? __('Save') ?>"/>
				<input type="button" class="btn btn-cancel" onclick="location.href='/admin/admin_group';" value="<? __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>
