<ol class="breadcrumb">
	<li><a href="/"><?= __('Main'); ?></a></li>
	<li class="active">404</li>
</ol>

<h2 class="main-heading text-center">
	<?= __('Error 404'); ?>
</h2>

<div class="content-box text-center">
	<h4 class="special-heading"><?= __('oops !'); ?></h4>
	<h5>
		<?= __('The page you were looking for could not be found.'); ?>
	</h5>
	<br/>
	<p>
		<a href="/" class="btn btn-brown text-uppercase"><?= __('Back to Home'); ?></a>
	</p>
</div>
