<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
	<meta name="keywords" content="<?php echo $vars['meta']['keywords']; ?>">
	<meta name="description" content="<?php echo $vars['meta']['description']; ?>">
	<meta name="author" content="Vitaliy Malyshev">

	<title><?php echo $vars['meta']['title']; ?></title>

	<?php echo $this->loadResources('css'); ?>
	<?php echo $this->loadResources('js'); ?>

	<link href="http://fonts.googleapis.com/css?family=Roboto+Condensed:300italic,400italic,700italic,400,300,700" rel="stylesheet" type="text/css">
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
	<link rel="shortcut icon" href="/storage/images/favicon.png">
</head>
<body>
<?php
	include 'header.phtml';
	include 'content.phtml';
	include 'footer.phtml';
?>
</body>
</html>