<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<!--[if IE]>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<![endif]-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="keywords" content="<?php echo $vars['meta']['keywords']; ?>">
	<meta name="description" content="<?php echo $vars['meta']['description']; ?>">
	<meta name="author" content="Vitaliy Malyshev">

	<title><?php echo $vars['meta']['title']; ?></title>

	<?php echo $this->loadResources('css'); ?>
	<?php echo $this->loadResources('js'); ?>

	<link href="http://fonts.googleapis.com/css?family=Roboto+Condensed:300italic,400italic,700italic,400,300,700"
		  rel="stylesheet" type="text/css">
	<link
		href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
		rel='stylesheet' type='text/css'>

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->

	<link rel="shortcut icon" href="/storage/images/favicon.png">
</head>
<body>
<header id="header-area">
	<?php include 'menu.phtml'; ?>
	<div class="container">
		<div class="main-header">
			<div class="row">

				<div class="col-md-3">
					<div id="search">
						<form action="/catalog/search">
						<div class="input-group">
							<input type="text" name="search" class="form-control input-lg" placeholder="<?= __('Search'); ?>" value="<?= isset($vars['search']) ? $vars['search'] : '';?>"/>
							  <span class="input-group-btn">
								<button class="btn btn-lg" type="button">
									<i class="fa fa-search"></i>
								</button>
							  </span>
						</div>
						</form>
					</div>
				</div>

				<div class="col-md-6">
					<div id="logo">
						<a href="/"><img src="/public/fashion/images/logo.png" title="<?=\Admin\Object\Setting::get('sitename');?>" alt="<?=\Admin\Object\Setting::get('sitename');?>" class="img-responsive"/></a>
					</div>
				</div>

				<?php include 'basket.phtml'; ?>

			</div>
		</div>
		<?php include 'cat_menu.phtml'; ?>
	</div>
</header>

<?php
	switch ($vars['controller']) {
		case 'Index':
			echo $vars['content'];
			break;
		default:
			echo '<div id="main-container" class="container">' . $vars['content'] . '</div>';
	}
?>

<footer id="footer-area">
	<div class="footer-links">
		<?php include 'menu_bottom.phtml'; ?>
	</div>
	<div class="copyright">
		<div class="container">
			<p class="pull-left">
				&copy; 2017 - <?=\Admin\Object\Setting::get('sitename');?>
			</p>
			<ul class="pull-right list-inline">
				<li>
					<img src="/public/fashion/images/payment-icon/cirrus.png" alt="PaymentGateway"/>
				</li>
				<li>
					<img src="/public/fashion/images/payment-icon/visa.png" alt="PaymentGateway"/>
				</li>
				<li>
					<img src="/public/fashion/images/payment-icon/mastercard.png" alt="PaymentGateway"/>
				</li>
			</ul>
		</div>
	</div>
</footer>
</body>
</html>