<?php if (sizeof($vars['comments']) == 0) echo __('No comments yet').'<br/><br/>'; ?>

<div class="col-lg-12 comments-list">
	<div class="row">
		<?php
		$i = 0;
		foreach ($vars['comments'] as $comment) { ?>
			<div class="row" data-id="<?=$comment['id'];?>">
				<div class="col-lg-12">
				<p>
					<b><?= $comment['user']; ?></b>
				</p>
				<p>
					<?= $comment['text']; ?>
				</p>
				<p class="text-muted small">
					<?= _libDate::date_view($comment['date'], 'dd MM YY'); ?>
				</p>
				<br/>
				</div>
			</div>
		<?php } ?>
	</div>
</div>

<?php if (!\Core\App::get()->getUser()) { ?>
	<div class="col-lg-12">
		<div class="row">
			<p class="small"><?= __('Authorization required for posting comments'); ?>:
				&nbsp;
			<a href="/user/login"><?= __('Login'); ?></a> |
			<a href="/user/register"><?= __('Register'); ?></a></p>
		</div>
	</div>
<?php } else { ?>

	<div class="col-lg-12 ">
		<div class="row">
			<div class="form-group">
				<input class="form-control comment-text" autocomplete="off" placeholder="<?= __('Leave a comment'); ?>..." name="comment" value=""/>
			</div>
			<div class="form-group comment-controls invisible">
				<input type="button" class="btn btn-sm btn-default comment-cancel" value="<?= __('Cancel') ?>"/>
				<input type="submit" class="btn btn-sm btn-brown comment-send" value="<?= __('Send') ?>"/>
			</div>
		</div>
	</div>
<?php } ?>

<script>
	$(document).ready(function () {
		Comments.initialize('<?=$vars['comments_type'];?>', <?=$vars['comments_type_id'];?>);
	});
</script>
