<div class="col-lg-12">
	<div class="row comments-list">
		<i class="fa fa-spinner"></i>
	</div>
</div>

<div class="col-lg-12">
	<div class="row">
		<a href="/product/comments/<?=$vars['product']['url'];?>"><?= __('go to comments page'); ?></a> <br/> <br/>
	</div>
</div>

<?php include 'comments/form.phtml'; ?>

<script>
	$(document).ready(function () {
		Comments.initialize('<?=$vars['comments_type'];?>', <?=$vars['comments_type_id'];?>, 10);
		Comments.list();
	});
</script>
