<!-- Breadcrumb Starts -->
<ol class="breadcrumb">
	<li><a href="/"><?= __('Main'); ?></a></li>
	<li class="active"><?= __('Contact Us'); ?></li>
</ol>

<h2 class="main-heading text-center">
	<?= __('Contact Us'); ?>
</h2>

<div class="row">
	<!-- Contact Details Starts -->
	<div class="col-sm-4">
		<div class="panel panel-smart">
			<div class="panel-heading">
				<h3 class="panel-title"><?= __('Contact Us'); ?></h3>
			</div>
			<div class="panel-body">
				<ul class="list-unstyled contact-details">
					<li class="clearfix">
						<i class="fa fa-home pull-left"></i>
								<span class="pull-left">
									My Company <br/>
									1247 LB Nagar Road, Hyderabad, <br/>
									Telangana - 500 035
								</span>
					</li>
					<li class="clearfix">
						<i class="fa fa-phone pull-left"></i>
								<span class="pull-left">
									91 99887 74455 <br/>
									001 123 974 9856
								</span>
					</li>
					<li class="clearfix">
						<i class="fa fa-envelope-o pull-left"></i>
								<span class="pull-left">
									info@demolink.com <br/>
									admin@demolink.com <br/>
									support@demolink.com
								</span>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- Contact Details Ends -->
	<!-- Contact Form Starts -->
	<div class="col-sm-8">
		<div class="panel panel-smart">
			<div class="panel-heading"><h3 class="panel-title"><?= __('Send us a email'); ?></h3>
			</div>
			<div class="panel-body">
				<form class="form-horizontal" role="form">
					<div class="form-group">
						<label for="name" class="col-sm-2 control-label">
							<?= __('Name'); ?>
						</label>
						<div class="col-sm-10">
							<input type="text" class="form-control" name="name" id="name" placeholder="<?= __('Name'); ?>">
						</div>
					</div>
					<div class="form-group">
						<label for="email" class="col-sm-2 control-label">
							Email
						</label>
						<div class="col-sm-10">
							<input type="email" class="form-control" name="email" id="email" placeholder="Email">
						</div>
					</div>
					<div class="form-group">
						<label for="subject" class="col-sm-2 control-label">
							<?= __('Subject'); ?>
						</label>
						<div class="col-sm-10">
							<input type="text" class="form-control" name="subject" id="subject"
								   placeholder="<?= __('Subject'); ?>">
						</div>
					</div>
					<div class="form-group">
						<label for="message" class="col-sm-2 control-label">
							<?= __('Message'); ?>
						</label>
						<div class="col-sm-10">
								<textarea name="message" id="message" class="form-control" rows="5"
										  placeholder="<?= __('Message'); ?>"></textarea>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<button type="submit" class="btn btn-brown text-uppercase">	<?= __('Submit'); ?></button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>

</div>