<footer id="footer-area">
	<div class="footer-links">
		<?php include 'menu_bottom.phtml'; ?>
	</div>
	<div class="copyright">
		<div class="container">
			<p class="pull-left">
				&copy; 2017 - <?=\Admin\Object\Setting::get('sitename');?>
			</p>
			<ul class="pull-right list-inline">
				<li>
					<img src="/public/fashion/images/payment-icon/cirrus.png" alt="PaymentGateway"/>
				</li>
				<li>
					<img src="/public/fashion/images/payment-icon/visa.png" alt="PaymentGateway"/>
				</li>
				<li>
					<img src="/public/fashion/images/payment-icon/mastercard.png" alt="PaymentGateway"/>
				</li>
			</ul>
		</div>
	</div>
</footer>