<section class="registration-area">
	<form role="form" action="/cart/order">
		<div class="row">
			<div class="col-sm-6">
				<div class="panel panel-smart form-horizontal">
					<div class="panel-heading">
						<h3 class="panel-title">
							<?= __('Shipment information'); ?>
						</h3>
					</div>
					<div class="panel-body">
						<div class="form-group">
							<label for="delivery" class="control-label col-sm-3"><?= __('Delivery Type') ?>:</label>
							<div class="col-sm-9">
								<select class="form-control" name="delivery">
									<?php foreach ($vars['delivery_types'] as $type) { ?>
										<option value="<?= $type['id']; ?>"><?= $type['name']; ?></option>
									<?php } ?>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label for="payment" class="col-sm-3 control-label"><?= __('Payment Type') ?>:</label>
							<div class="col-sm-9">
								<select class="form-control" name="payment">
									<?php foreach ($vars['payment_types'] as $type) { ?>
										<option value="<?= $type['id']; ?>"><?= $type['name']; ?></option>
									<?php } ?>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label"><?= __('City') ?>:</label>
							<div class="col-sm-9">
								<input class="form-control" name="city" value="<?= $vars['userinfo']['city']; ?>"/>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label"><?= __('Address') ?>:</label>
							<div class="col-sm-9">
								<input class="form-control" name="address"
									   value="<?= $vars['userinfo']['address']; ?>"/>
							</div>
						</div>
					</div>
				</div>

			</div>
			<div class="col-sm-6">
				<div class="panel panel-smart form-horizontal">
					<div class="panel-heading">
						<h3 class="panel-title">
							<?= __('User information'); ?>
						</h3>
					</div>
					<div class="panel-body">
						<div class="form-group">
							<label class="col-sm-3 control-label"><?= __('First name') ?>:</label>
							<div class="col-sm-9">
								<input class="form-control" name="firstName"
									   value="<?= $vars['userinfo']['firstName']; ?>"/>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label"><?= __('Last name') ?>:</label>
							<div class="col-sm-9">
								<input class="form-control" name="lastName"
									   value="<?= $vars['userinfo']['lastName']; ?>"/>
							</div>
						</div>
						<div class="form-group">
							<label for="inputEmail" class="col-sm-3 control-label"><?= __('E-Mail') ?>:</label>
							<div class="col-sm-9">
								<input class="form-control" name="email" value="<?= $vars['userinfo']['email']; ?>"/>
							</div>
						</div>
						<div class="form-group">
							<label for="inputPhone" class="col-sm-3 control-label"><?= __('Phone') ?>:</label>
							<div class="col-sm-9">
								<input class="form-control" name="phone" value="<?= $vars['userinfo']['phone']; ?>"/>
							</div>
						</div>

						<div class="form-group">
							<label class="col-sm-3 control-label"><?= __('Comment') ?>:</label>
							<div class="col-sm-9">
								<textarea class="form-control" name="comment" style="resize:none;"></textarea>
							</div>
						</div>

					</div>
				</div>

			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="form-group">
					<div class="col-sm-offset-5 col-sm-12">
						<button type="submit" class="btn btn-brown">
							<?= __('Order'); ?>
						</button>
					</div>
				</div>
			</div>
		</div>
	</form>
</section>