<div class="row">
	<div class="col-lg-12">
		<?php echo $vars['breadcrumbs']; ?>
	</div>
</div>

<div class="row product-info full">
	<div class="col-sm-8 images-block">
		<div class="carousel" style="height:510px;">
			<?php foreach ($vars['photos'] as $photo) { ?>
				<div class="photo">
					<a href="/api.php?method=Resource.get&id=<?= $photo['original']; ?>">
						<img src="/api.php?method=Resource.get&id=<?= $photo['photo']; ?>" class="img-responsive" />
					</a>
				</div>
			<?php } ?>
		</div>

		<div class="carousel-preview">
			<div class="row">
				<?php $i = 0; foreach ($vars['photos'] as $photo) { ?>
					<div class="item col-sm-2" data-num="<?=$i++;?>" >
						<img src="/api.php?method=Resource.get&id=<?= $photo['preview']; ?>" class="thumbnail img-responsive"/>
					</div>
					<?php if ($i % 6 === 0) echo '</div><div class="row">'?>
				<?php } ?>
			</div>
		</div>
	</div>

	<div class="col-sm-4 product-details">
		<div class="panel-smart">
			<h2><?= $vars['product']['name']; ?></h2>
			<hr/>

			<ul class="list-unstyled manufacturer">
				<li>
					<span><?= __('Availability');?>:</span>
					<strong class="label <?= ($vars['product']['status'] == 1) ? 'label-success' : 'label-danger'; ?>"><?= $vars['product']['status_text']; ?></strong>
				</li>
			</ul>

			<hr/>

			<div class="price">
				<span class="price-head"><?= __('Price');?>:</span>
				<span class="price-new"><?= \App\Service\Product::viewPrice($vars['product']['price']); ?></span>
			</div>

			<hr/>

			<div class="options">
				<h3><?= __('Description'); ?></h3>

				<div class="form-group">
					<p><?= htmlspecialchars_decode($vars['product']['text']); ?></p>
				</div>

				<div class="cart-button button-group">
					<button type="button" class="btn btn-cart" onclick="addToCart(<?=$vars['product']['id'];?>);">
						<?= __('Add to cart');?>
						<i class="fa fa-shopping-cart"></i>
					</button>
					<span class="alert alert-success cart-added"><?= __('Added to cart'); ?></span>
				</div>
			</div>
		</div>
	</div>
</div>


<h3><?= __('Comments'); ?> <a href="/product/comments/<?=$vars['product']['url'];?>">(<?= __('view all'); ?>)</a></h3>
<?php
	$vars['comments_type'] = 'Product';
	$vars['comments_type_id'] = $vars['product']['id'];
	include 'comments.phtml';
?>

<div class="row"><br/></div>

<h3><?= __('Recommended products'); ?></h3>

<div class="row">
	<?php
	foreach ($vars['recommended'] as $product) {
		include 'index/product.phtml';
	} ?>
</div>

<script>
	$('.carousel .photo').hide();
	$('.carousel .photo').first().show();

	$('.carousel-preview .item').on('click', function() {
		$('.carousel-preview .item').removeClass('active');
		$(this).addClass('active');
		$('.carousel .photo').hide();
		$($('.carousel .photo')[$(this).data('num')]).show();
	});
</script>