<div class="row">
	<div class="col-lg-12">
		<?php echo $vars['breadcrumbs']; ?>
	</div>
</div>


<h2 class="main-heading text-center">
	<?= __('Comments'); ?>
</h2>
<h4 class="text-center"><?= __('for product') ?> <a href="/product/view/<?=$vars['product']['url'];?>"><?=$vars['product']['name'];?></a></h4>

<div class="col-lg-12">
	<?php include 'comments/list.phtml'; ?>
</div>

<div class="col-lg-12">
	<div class="row"><br/></div>
</div>
<?php include 'comments/form.phtml'; ?>

<script>
	$(document).ready(function () {
		Comments.initialize('product', <?=$vars['product']['id'];?>);
	});
</script>

