<div class="row">
	<div class="col-lg-12">
		<?php echo $vars['breadcrumbs']; ?>
	</div>
</div>

<div class="row product-info full">
	<div class="col-sm-8 images-block">
		<div class="carousel">
			<?php foreach ($vars['photos'] as $photo) { ?>
				<div class="photo">
					<a href="/api.php?method=Resource.get&id=<?= $photo['original']; ?>">
						<img data-zoom="/api.php?method=Resource.get&id=<?= $photo['original']; ?>" src="/api.php?method=Resource.get&id=<?= $photo['photo']; ?>" class="img-responsive" />
					</a>
				</div>
			<?php } ?>
		</div>
		<div class="row"><br/></div>
		<div class="carousel-preview">
			<div class="row">
				<?php $i = 0; foreach ($vars['photos'] as $photo) { ?>
					<div class="item col-xs-2 col-sm-2 col-md-2 col-lg-2" data-num="<?=$i++;?>" >
						<img src="/api.php?method=Resource.get&id=<?= $photo['preview']; ?>" class=" img-responsive"/>
					</div>
					<?php if ($i % 6 === 0) echo '</div><div class="row">'?>
				<?php } ?>
			</div>
		</div>
		<br/>
	</div>

	<div class="col-sm-4 product-details">
		<div class="panel-smart">
			<h2><?= $vars['product']['name']; ?></h2>
			<hr/>

			<ul class="list-unstyled manufacturer">
				<li>
					<span><?= __('Availability');?>:</span>
					<strong class="label <?= ($vars['product']['status'] == 1) ? 'label-success' : 'label-danger'; ?>"><?= $vars['product']['status_text']; ?></strong>
				</li>
			</ul>

			<hr/>

			<div class="price">
				<span class="price-head"><?= __('Price');?>:</span>
				<span class="price-new"><?= \App\Service\Product::viewPrice($vars['product']['price']); ?></span>
			</div>

			<hr/>

			<div class="options">
				<h3><?= __('Description'); ?></h3>

				<div class="form-group">
					<p><?= htmlspecialchars_decode($vars['product']['text_m']); ?></p>
				</div>

				<?php if ($vars['product']['status'] == 1) { ?>
				<div class="cart-button button-group">
					<button type="button" class="btn btn-cart" onclick="addToCart(<?=$vars['product']['id'];?>);">
						<?= __('Add to cart');?>
						<i class="fa fa-shopping-cart"></i>
					</button>
					<span class="alert alert-success cart-added"><?= __('Added to cart'); ?></span>
				</div>
				<?php } ?>
			</div>
		</div>
	</div>
</div>

<div class="tabs-panel panel-smart">
	<ul class="nav nav-tabs">
		<li class="active"><a href="#tab-ainfo"><?= __('Description'); ?></a></li>
		<li class=""><a href="#tab-review"><?= __('Comments'); ?></a></li>
	</ul>
	<div class="tab-content clearfix">
		<div class="tab-pane active" id="tab-ainfo">
			<p><?= htmlspecialchars_decode($vars['product']['text']); ?></p>
		</div>
		<div class="tab-pane" id="tab-review">
			<?php
			$vars['comments_type'] = 'Product';
			$vars['comments_type_id'] = $vars['product']['id'];
			include 'comments.phtml';
			?>
		</div>
	</div>
</div>

<div class="product-info-box">
<h4 class="heading"><?= __('Recommended products'); ?></h4>

<div class="row">
	<?php
	foreach ($vars['recommended'] as $product) {
		include 'index/product.phtml';
	} ?>
</div>
</div>

<script>
	$(document).ready( function() {
		$('.nav-tabs a').click(function (e) {
			e.preventDefault();
			$(this).tab('show');
		});

		$('.carousel .photo').hide();
		$('.carousel .photo').first().show();
		$('.carousel-preview .item').first().addClass('active');

		$('.carousel-preview .item').on('click', function() {
			$('.carousel-preview .item').removeClass('active');
			$(this).addClass('active');
			$('.carousel .photo').hide();
			$($('.carousel .photo')[$(this).data('num')]).show();
		});

		var photos = document.querySelectorAll('.carousel .photo a img');

		for (var i =0; i < photos.length; i++) {
			new Drift(photos[i], {
				paneContainer: document.querySelector('.product-details > .panel-smart')
			}).enable();
		}

	});

</script>