<div class="row">
	<div class="col-lg-12">
		<?php echo $vars['breadcrumbs']; ?>
	</div>
</div>


<h2 class="main-heading text-center">
	<?= __('Comments'); ?>
</h2>
<h4 class="text-center"><?= __('for product') ?> <?=$vars['product']['name'];?></h4>

<div class="col-lg-12 comments-list">
	<div class="row">
		<?php
		$i = 0;
		foreach ($vars['comments'] as $comment) { ?>
			<div class="row" data-id="<?=$comment['id'];?>">
				<div class="col-lg-12">
					<p>
						<b><?= $comment['user']; ?></b>
					</p>
					<p>
						<?= $comment['text']; ?>
					</p>
					<br/>
				</div>
			</div>
		<?php } ?>
	</div>
</div>

<?php if (!\Core\App::get()->getUser()) { ?>
	<div class="col-lg-12">
		<div class="row">
			<?= __('Authorization required for posting comments'); ?>:
			<a href="/user/login"><?= __('Login'); ?></a> |
			<a href="/user/register"><?= __('Register'); ?></a>
		</div>
	</div>
<?php } else { ?>

	<div class="col-lg-12 ">
		<div class="row">
			<div class="form-group">
				<input class="form-control comment-text" autocomplete="off" placeholder="<?= __('Leave a comment'); ?>..." name="comment" value=""/>
			</div>
			<div class="form-group comment-controls invisible">
				<input type="button" class="btn btn-sm btn-default comment-cancel" value="<?= __('Cancel') ?>"/>
				<input type="submit" class="btn btn-sm btn-brown comment-send" value="<?= __('Send') ?>"/>
			</div>
		</div>
	</div>
<?php } ?>

<script>
	$(document).ready(function () {
		Comments.initialize('product', <?=$vars['product']['id'];?>);
	});
</script>

