<form role="form" action="/product/order">
	<input type="hidden" name="id" value="<?= $vars['product']['id']; ?>" />
	<div class="form-group">
		<label><?= __('First name') ?></label>
		<input class="form-control" name="firstName" value="<?= $vars['userinfo']['firstName'];?>"/>
	</div>
	<div class="form-group">
		<label><?= __('Last name') ?></label>
		<input class="form-control" name="lastName" value="<?= $vars['userinfo']['lastName'];?>"/>
	</div>
	<div class="form-group">
		<label><?= __('E-Mail') ?></label>
		<input class="form-control" name="email" value="<?= $vars['userinfo']['email'];?>"/>
	</div>
	<div class="form-group">
		<label><?= __('Phone') ?></label>
		<input class="form-control" name="phone" value="<?= $vars['userinfo']['phone'];?>"/>
	</div>
	<div class="form-group">
		<label><?= __('Payment Type') ?></label>
		<select class="form-control" name="payment">
			<?php foreach ($vars['payment_types'] as $type) { ?>
				<option value="<?= $type['id'];?>"><?= $type['name'];?></option>
			<?php } ?>
		</select>
	</div>
	<div class="form-group">
		<label><?= __('Delivery Type') ?></label>
		<select class="form-control" name="delivery">
			<?php foreach ($vars['delivery_types'] as $type) { ?>
				<option value="<?= $type['id'];?>"><?= $type['name'];?></option>
			<?php } ?>
		</select>
	</div>
	<div class="form-group">
		<label><?= __('Address') ?></label>
		<input class="form-control" name="address" value="<?=$vars['userinfo']['address'];?>"/>
	</div>
	<div class="form-group">
		<label><?= __('Comment') ?></label>
		<textarea class="form-control" name="comment" style="resize:vertical;"></textarea>
	</div>
	<div class="form-group">
		<input type="submit" class="btn btn-success" value="<?= __('Order') ?>"/>
	</div>
</form>