<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Edit page') ?> - <?=$vars['page']['name'];?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>


<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
	<li role="presentation" class="active"><a href="#info" aria-controls="info" role="tab" data-toggle="tab"><?= __('Information') ;?></a></li>
	<li role="presentation"><a href="#meta" aria-controls="meta" role="tab" data-toggle="tab"><?= __('Meta data') ;?></a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
	<div role="tabpanel" class="tab-pane active" id="info">
		<div class="row">
			<div class="col-lg-12">
				<form role="form" action="/admin/page/save">
					<input type="hidden" name="id" value="<?= $vars['page']['id']; ?>"/>
					<div class="form-group">
						<label><?= __('Name') ?></label>
						<input class="form-control" name="name" value="<?= $vars['page']['name']; ?>"/>
					</div>
					<div class="form-group">
						<label><?= __('Url') ?></label>
						<input class="form-control" name="url" value="<?= $vars['page']['url']; ?>"/>
					</div>
					<div class="form-group">
						<label><?= __('Text') ?></label>
						<textarea id="editor-1" class="form-control" name="text"><?= $vars['page']['text']; ?></textarea>
						<script>//CKEDITOR.replace('editor-1');</script>
						<script>
							CKEDITOR.replace( 'editor-1', {
								filebrowserBrowseUrl: '/public/admin/js/ckfinder/ckfinder.html',
								filebrowserUploadUrl: '/public/admin/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
								filebrowserWindowWidth: '1000',
								filebrowserWindowHeight: '700'
							} );
						</script>
					</div>
					<div class="form-group">
						<input type="submit" class="btn btn-default" value="<?= __('Save') ?>"/>
						<input type="button" class="btn btn-cancel" onclick="location.href='/admin/page';" value="<?= __('Cancel') ?>"/>
					</div>
				</form>
			</div>
		</div>
	</div>
	<div role="tabpanel" class="tab-pane" id="meta">
		<form role="form" action="/admin/meta/update">
			<input type="hidden" name="moduleId" value="<?= $vars['moduleId']; ?>"/>
			<input type="hidden" name="url" value="<?= $vars['page']['url']; ?>"/>
			<div class="form-group">
				<label>Title</label>
				<input class="form-control" name="title" value="<?= $vars['meta']['title']; ?>"/>
			</div>
			<div class="form-group">
				<label>Keywords</label>
				<input class="form-control" name="keywords" value="<?= $vars['meta']['keywords']; ?>"/>
			</div>
			<div class="form-group">
				<label>Description</label>
				<input class="form-control" name="description" value="<?= $vars['meta']['description']; ?>"/>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-default" value="<?= __('Save') ?>"/>
				<input type="button" class="btn btn-cancel" onclick="location.href='/admin/page';" value="<?= __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>