<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header">Add new page</h3>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="save">
		    <div class="form-group">
		        <label>Name</label>
		        <input class="form-control" name="name" value="" />
		    </div>
		    <div class="form-group">
		        <label>URL</label>
		        <input class="form-control" name="url" value="" />
		    </div>
		    <div class="form-group">
		        <label>Description</label>
		        <textarea id="editor" class="form-control" name="text"></textarea>
		    </div>
		   	 <div class="form-group">
		        <input type="submit" class="btn btn-default" value="Save" />
		        <input type="button" class="btn btn-cancel" onclick="location.href='/admin/page';" value="Cancel" />
		    </div>
		</form>
	</div>
</div>

<script>
	CKEDITOR.replace('editor');
</script>
