<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header">Edit page - <?=$vars['page']['name'];?></h3>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="save">
			<input type="hidden" name="id" value="<?=$vars['page']['id'];?>"/>
		    <div class="form-group">
		        <label>Name</label>
		        <input class="form-control" name="name" value="<?=$vars['page']['name'];?>"/>
		    </div>
		    <div class="form-group">
		        <label>URL</label>
		        <input class="form-control" name="url" value="<?=$vars['page']['url'];?>"/>
		    </div>
		    <div class="form-group">
		        <label>Description</label>
		        <textarea id="editor" class="form-control" name="text"><?=$vars['page']['text'];?></textarea>
		    </div>
		   	 <div class="form-group">
		        <input type="submit" class="btn btn-default" value="Save" />
		        <input type="button" class="btn btn-cancel" onclick="location.href='/admin/page';" value="Cancel" />
		    </div>
		</form>
	</div>
</div>

<script>
	CKEDITOR.replace('editor');
</script>
