<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Pages</h1>
	</div>
</div>


<div class="row">
	<div class="col-lg-6">
		<button class="btn btn-primary" onclick="location.href='/admin/page/add'">Add new</button>
	</div>
</div>

<br/>
<div class="dataTable_wrapper">
	<div class="dataTables_wrapper form-inline dt-bootstrap no-footer">

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-info">
					<div class="panel-heading">
						Pages list
					</div>
					<!-- /.panel-heading -->
					<div class="panel-body">
							<table class="table table-hover table-striped table-bordered dataTable">
								<thead>
									<tr>
										<th>#</th>
										<th>Name</th>
										<th>Url</th>
										<th width="90">Actions</th>
									</tr>
								</thead>
								<tbody>
									<?php 
										foreach ($vars['pages'] as $row) {
											echo '
	                                            <tr>
		                                            <td>' . $row['id'] . '</td>
		                                            <td>' . $row['name'] . '</td>
		                                            <td>' . $row['url'] . '</td>
		                                            <td>
		                                            <a class="blue" href="/admin/page/edit/' . $row['id'] . '"><i class="fa fa-pencil"></i> Edit</a> |
		                                            <a class="red" href="/admin/page/delete/' . $row['id'] . '"><i class="fa fa-times"></i> Delete</a>
		                                            </td>
		                                        </tr>';
										}
									?>
								</tbody>
							</table>
					</div>
				</div>
			</div>
		</div>

		<?= $vars['paging'] ;?>
	</div>
</div>