<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Pages</h1>
	</div>
</div>


<div class="row">
	<div class="col-lg-6">
		<button class="btn btn-primary" onclick="location.href='/admin/page/add'">Add new</button>
	</div>
</div>

<br/>
<div class="dataTable_wrapper">
	<div class="dataTables_wrapper form-inline dt-bootstrap no-footer">

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						Pages list
					</div>
					<!-- /.panel-heading -->
					<div class="panel-body">
						<div class="table-responsive">
							<table class="table table-hover">
								<thead>
									<tr>
										<th>#</th>
										<th>Name</th>
										<th>Url</th>
										<th>Actions</th>
									</tr>
								</thead>
								<tbody>
									<?php 
										foreach ($vars['pages'] as $row) {
											echo '
	                                        	<tr>
		                                            <td>' . $row['id'] . '</td>
		                                            <td>' . $row['name'] . '</td>
		                                            <td>' . $row['url'] . '</td>
		                                            <td>
		                                            <a href="/admin/page/edit?id=' . $row['id'] . '">Edit</a> | 
		                                            <a href="/admin/page/delete?id=' . $row['id'] . '">Delete</a>
		                                            </td>
		                                        </tr>';
										}
									?>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-6">
				<div class="dataTables_info" id="dataTables-example_info" role="status" aria-live="polite">Showing <?=$vars['offset'];?> to
					<?=$vars['limit'];?> of <?=$vars['total'];?> entries
				</div>
			</div>
			<div class="col-lg-6">
				<div class="dataTables_paginate paging_simple_numbers" id="dataTables-example_paginate">
					<ul class="pagination">

						<?php
							if ($vars['total'] > count($vars['pages'])) {

								if ($vars['page'] > 1) echo '<li class="paginate_button previous" aria-controls="dataTables-example" tabindex="0"
						    id="dataTables-example_previous"><a href="?page='.($vars['page'] - 1).'">Previous</a></li>';

							for ($page = 1; ($page-1) * $vars['onpage'] < $vars['total']; $page++) {
						?>

							<li class="paginate_button " aria-controls="dataTables-example" tabindex="0"><a href="?page=<?=$page;?>">
									<?=$page;?>
								</a>
							</li>

						<?php }

							if ($vars['page']*$vars['onpage'] < $vars['total']) echo '<li class="paginate_button next" aria-controls="dataTables-example" tabindex="0"
						    id="dataTables-example_next"><a href="?page='.($vars['page']+1).'">Next</a></li>';

							} ?>

					</ul>
				</div>
			</div>
		</div>
	</div>
</div>