<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Pages</h1>
	</div>
</div>


<div class="row">
	<div class="col-lg-6">
		<button class="btn btn-primary" onclick="location.href='/admin/page/add'">Add new</button>
	</div>
</div>

<br/>
<div class="dataTable_wrapper">
	<div class="dataTables_wrapper">

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-info">
					<div class="panel-heading">
						Pages list
					</div>
					<!-- /.panel-heading -->
					<div class="panel-body">
							<table class="table table-bordered dataTable">
								<thead>
									<tr>
										<th>#</th>
										<th>Name</th>
										<th>Url</th>
										<th>Active</th>
										<th width="130">Actions</th>
									</tr>
								</thead>
								<tbody>
									<?php 
										foreach ($vars['pages'] as $row) {
											echo '
	                                            <tr>
		                                            <td>' . $row['id'] . '</td>
		                                            <td>' . $row['name'] . '</td>
		                                            <td>' . $row['url'] . '</td>
		                                            <td>
														<input class="switcher" type="checkbox" name="active" checked />
		                                            </td>
		                                            <td>
														<div class="btn-group btn-sm">
														  <a href="page/edit/' . $row['id'] . '" class="btn btn-sm btn-default">Edit</a>
														  <button class="btn dropdown-toggle btn-sm btn-default" data-toggle="dropdown">
														    <span class="caret"></span>
														  </button>
														  <ul class="dropdown-menu">
														    <li><a href="page/edit/duplicate/' . $row['id'] . '">Duplicate</a></li>
														    <li><a href="page/edit/delete/' . $row['id'] . '">Delete</a></li>
														  </ul>
														</div>
		                                       
		                                            </td>
		                                        </tr>';
										}
									?>
								</tbody>
							</table>
					</div>
				</div>
			</div>
		</div>

		<?= $vars['paging'] ;?>
	</div>
</div>

<script>
	$('.switcher').bootstrapSwitch({
		size: "mini",
		onSwitchChange: function(event, state) {
			event.preventDefault();
			console.log(state);
		}
	});
</script>