<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Admin Dashboard</title>

    <?php echo $this->getResources('css'); ?>

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <?php echo $this->load('phtml', '/templates/topbar.phtml'); ?>
            <?php echo $this->load('phtml', '/templates/sidebar.phtml'); ?>
        </nav>
        <div id="page-wrapper">
            <?php echo $vars['content']; ?>
        </div>
    </div>

    <?php echo $this->getResources('js'); ?>

</body>
</html>
