
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><?__('Dashboard');?></h1>
                </div>
                <div class="col-lg-12">
                    <h2><?__('Modules');?></h2>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-2">
                    <a class="fa fa-copy" href="/admin/page"> <?__('Pages');?></a>
                </div>

                <div class="col-lg-2">
                    <a class="fa fa-rocket" href="/admin/admin"> <?__('Administrators');?></a>
                </div>
            </div>