
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Dashboard</h1>
                </div>
                <div class="col-lg-12">
                    <h2>Modules</h2>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-2">
                    <a class="fa fa-copy" href="/admin/page"> Pages</a>
                </div>

                <div class="col-lg-2">
                    <a class="fa fa-rocket" href="/admin/admin"> Administrators</a>
                </div>
            </div>