<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"><?= __('Nova Poshta') ?></h1>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<button class="btn btn-primary" onclick="location.href='/admin/nova_poshta/refresh_cities'"><?= __('Parse cities') ?></button>
		<button class="btn btn-primary" onclick="location.href='/admin/nova_poshta/refresh_warehouses'"><?= __('Update warehouses') ?></button>
	</div>
</div>

<br/>
<div class="dataTable_wrapper">
	<div class="dataTables_wrapper">
		<div class="row">
			<div class="col-lg-12">
				<table class="table table-bordered dataTable">
					<thead>
					<tr>
						<th>ID</th>
						<th><?= __('Name') ?></th>
						<th><?= __('Updated') ?></th>
					</tr>
					</thead>
					<tbody>
					<?php
					foreach ($vars['cities'] as $row) {
						echo '
                        <tr>
                            <td>' . $row->id . '</td>
                            <td>' . $row->name_ru . '</td>
                            <td>' . $row->last_update . '</td>
                        </tr>';
					}
					?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
