<div class="row">
	<div class="col-lg-12">
		<?php echo $vars['breadcrumbs']; ?>
	</div>
</div>

<h1><?= $vars['album']['name']; ?></h1>

<div class="row">
	<div class="col-lg-12">
		<div id="photos-list">
			<div class="col-lg-12">
				<div class="row">
					<?php
					$i = 0;
					foreach ($vars['photos'] as $photo) {
						if ($i++ % 4 === 0) echo '</div><div class="row">';
						echo '<img width="100%" src="/api.php?method=Resource.get&id=' . $photo['resourceId'] . '" />';
						echo '<br/><br/>';
					}
					?>
				</div>
			</div>
		</div>
	</div>
</div>
