<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Edit meta') ?> - <?=$vars['meta']['url'];?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/meta/save">
			<input type="hidden" name="id" value="<?= $vars['meta']['id']; ?>" />
			<div class="form-group">
				<label>Url</label>
				<input class="form-control" name="url" value="<?= $vars['meta']['url']; ?>" />
			</div>
			<div class="form-group">
				<label>Title</label>
				<input class="form-control" name="title" value="<?= $vars['meta']['title']; ?>" />
			</div>
			<div class="form-group">
				<label>Keywords</label>
				<input class="form-control" name="keywords" value="<?= $vars['meta']['keywords']; ?>" />
			</div>
			<div class="form-group">
				<label>Description</label>
				<input class="form-control" name="description" value="<?= $vars['meta']['description']; ?>" />
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="<?= __('Save') ?>"/>
				<input type="button" class="btn btn-primary" onclick="location.href='/admin/meta';" value="<?= __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>

