<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
	<meta name="keywords" content="<?php echo $vars['meta']['keywords']; ?>">
	<meta name="description" content="<?php echo $vars['meta']['description']; ?>">
	<meta name="author" content="Vitaliy Malyshev">
	<title><?php echo $vars['meta']['title']; ?></title>

	<?php echo $this->loadResources('css'); ?>
	<?php echo $this->loadResources('js'); ?>
</head>
<body>

<?php include 'menu.phtml'; ?>

<aside class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<?php if (isset($vars['breadcrumbs'])) echo $vars['breadcrumbs']; ?>
		</div>
	</div>
	<?php echo $vars['content']; ?>
</aside>
</body>
</html>
