<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>Site</title>

	<?php echo $this->loadResources('css'); ?>
	<?php echo $this->loadResources('js'); ?>

</head>
<body>
<section>
	<a href="/lang/?switch=ru" class="<?php echo $this->isCurrentLanguage('ru') ? 'active-language' : ''; ?>">RU</a> |
	<a href="/lang/?switch=en" class="<?php echo $this->isCurrentLanguage('en') ? 'active-language' : ''; ?>">EN</a>
</section>
<aside>
	<?php echo $vars['content']; ?>
</aside>
</body>
</html>
