<h1><? __('Cart'); ?></h1>

<div class="table-responsive">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>#</th>
				<th><? __('Name') ?></th>
				<th><? __('Count') ?></th>
				<th><? __('Price') ?></th>
				<th><? __('Sum') ?></th>
				<th><? __('Actions') ?></th>
			</tr>
		</thead>
		<tbody>
		<?php $counter = 1; ?>
		<?php foreach ($vars['cart'] as $item) { ?>
			<tr>
				<td><?= $counter++; ?></td>
				<td><?= $item['product']['name']; ?></td>
				<td><input type="number" value="<?= $item['count']; ?>"></td>
				<td><?= $item['product']['price']; ?></td>
				<td><?= number_format($item['product']['price']*$item['count'], 2); ?></td>
				<td>
					<a href="#" onclick="removeFromCart(<?= $item['id']; ?>);">remove</a> | 
					<a href="#" onclick="">update</a>
				</td>
			</tr>
		<?php } ?>
		</tbody>
	</table>
</div>
