<h1><? __('Catalog'); ?></h1>

<div class="row">
	<div class="col-lg-2">
		<ul class="nav nav-pills nav-stacked">
			<li role="presentation"><a href="/catalog/">Все категории</a></li>
			<?php
			foreach ($vars['catalogs'] as $cat) {
				$active = ($cat['id'] == $vars['catalog']) ? 'class="active"' : '';
				echo '<li role="presentation" ' . $active . '><a href="/catalog/' . $cat['url'] . '">' . $cat['name'] . '</a></li>';
			}
			?>
		</ul>

		<div id="catalog-filters">
			<?php
			foreach ($vars['filters'] as $cat) {
				echo '<p>' . $cat['name'] . '</p>';

				foreach ($cat['filters'] as $filter) {
					$checked = in_array($filter['id'], $vars['checked_filters']) ? 'checked' : '';
					echo '<label>
								<input '.$checked.' class="filter" value="'.$filter['id'].'" name="filter[]" type="checkbox">
								' . $filter['name'] . '</label><br/>';
				}
			}
			?>
		</div>
	</div>
	<div class="col-lg-10">
		<div class="row">
			<div class="col-lg-4">
					<div class="form-group">
						<label>Сортировка</label>
						<select class="form-control" name="sort" id="catalog-sort">
							<option <?= ($vars['sort'] == '') ? 'selected' : '' ?> value="">обычная</option>
							<option <?= ($vars['sort'] == 'price:asc') ? 'selected' : '' ?> value="price:asc">от дешевых к дорогим</option>
							<option <?= ($vars['sort'] == 'price:desc') ? 'selected' : '' ?> value="price:desc">от дорогих к дешевым</option>
						</select>
					</div>
			</div>
		</div>
		<div class="row">
			<div id="products-list">
				<?php include 'products_list.phtml'; ?>
			</div>
		</div>
	</div>
</div>

<script>
	$('#catalog-filters').on('click', function (e) {
		var elem = $(e.target);
		if (elem.hasClass('filter')) {
			requestProducts();
		}
	});

	$('#catalog-sort').on('change', function () {
		requestProducts();
	});

	function requestProducts()
	{
		var filters = [];
		$('#catalog-filters input[type=checkbox]').each(function (n, i) {
			if ($(i).is(':checked')) {
				filters.push($(i).val());
			}
		});

		$.ajax('/api.php?method=Catalog.products', {
			method: 'POST',
			data: {
				filters: filters,
				catalog: '<?=$vars['catalog']?>',
				sort: $('#catalog-sort').val()
			}
			,
			success: function (data) {
				$('#products-list').html(data.response);
			},
			error: function (e) {
				$('#products-list').html(e);
			}
		});
	}
</script>
