<h1><? __('Catalog'); ?></h1>

<div class="row">
	<div class="col-lg-2">
		<ul class="nav nav-pills nav-stacked">
			<?php
				foreach ($vars['catalogs'] as $cat) {
					$active = ($cat['id'] == $vars['catalog']) ? 'class="active"' : '';
					echo '<li role="presentation" '.$active.'><a href="/catalog/' . $cat['url'] . '">' . $cat['name'] . '</a></li>';
				}
			?>
		</ul>
	</div>
	<div class="col-lg-10">
		<?php
			foreach ($vars['products'] as $product) {
				include 'product.phtml';
			}
		?>
	</div>
</div>
