<h3><?= __('Comments'); ?></h3>
<?php if (count($vars['comments']) == 0) echo __('No comments yet'); ?>

<div class="col-lg-12 comments-list">
	<div class="row">
		<?php
		$i = 0;
		foreach ($vars['comments'] as $comment) { ?>
			<div class="col-lg-12" data-id="<?=$comment['id'];?>">
				<div class="row">
					<?= $comment['userId']; ?>
				</div>
				<div class="row">
					<?= $comment['text']; ?>
				</div>
				<!--<div class="row">
					<a class="comment-reply" href="#">Reply to comment</a>
				</div>-->
			</div>
		<?php } ?>
	</div>
</div>

<?php if (!\Core\App::get()->getUser()) { ?>
	<div class="col-lg-12">
		<div class="row">
			<?= __('Authorization required for posting comments'); ?>
			<a href="/user/login">login</a> |
			<a href="/user/register">register</a>
		</div>
	</div>
<?php } else { ?>

	<div class="col-lg-12 ">
		<div class="row">
			<br/>
			<div class="form-group">
				<input class="form-control comment-text" autocomplete="off" placeholder="<?= __('Leave a comment'); ?>..." name="comment" value=""/>
			</div>
			<div class="form-group comment-controls invisible">
				<input type="button" class="btn btn-sm btn-default comment-cancel" value="<?= __('Cancel') ?>"/>
				<input type="submit" class="btn btn-sm btn-info comment-send" value="<?= __('Send') ?>"/>
			</div>
		</div>
	</div>
<?php } ?>

<script>
	$(document).ready(function () {
		Comments.initialize('<?=$vars['comments_type'];?>', <?=$vars['comments_type_id'];?>);
	});
</script>
