<h3><?= __('Comments'); ?></h3>
<?php if (sizeof($vars['comments'] == 0)) echo __('No comments yet'); ?>

<div class="col-lg-12">
	<div class="row">
		<?php
		$i = 0;
		foreach ($vars['comments'] as $comment) { ?>
			<div class="col-lg-12">
				<div class="row">
					<?= $comment['userId']; ?>
				</div>
				<div class="row">
					<?= $comment['text']; ?>
				</div>
				<div class="row">
					<a href="#">Reply</a>
				</div>
			</div>
		<?php } ?>
	</div>
</div>

<?php if (!\Core\App::get()->getUser()) { ?>
	<div class="col-lg-12">
		<div class="row">
			<?= __('Authorization required for posting comments'); ?>
			<a href="/user/login">login</a> |
			<a href="/user/register">register</a>
		</div>
	</div>
<?php } else { ?>
	<div class="col-lg-12">
		<div class="row">
			<div class="form-group">
				<label><?= __('Comment') ?></label>
				<input class="form-control" name="comment" value=""/>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-default" value="<?= __('Send') ?>"/>
			</div>
		</div>
	</div>
<?php } ?>