<section>
	<h1>Sample main page</h1>


	<p>Page routes examples:</p>
	<a href="/page?page=my_super_url">/page?page=my_super_url</a> <br/>
	<a href="/pages?page=my_super_url">/pages?page=my_super_url</a>  <br/>
	<a href="/my_super_url">/my_super_url</a>  <br/>

	<p>How API and API routes examples:</p>
	<a href="/api.php?method=Page.index">/api.php?method=Page.index</a> <br/>
	<a href="/api.php?method=Page.get&id=1">/api.php?method=Page.get&id=1</a>  <br/>

</section>