<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">[Shop]</a>
		</div>

		<div class="nav navbar-top-links navbar-collapse">
			<ul class="nav navbar-nav ">
				<?php foreach ($vars['main_menu'] as $row) { ?>
					<? $active = (\Core\Router::get('uri') == $row['url']) ? 'class="active"' : '';?>
					<li <?=$active;?>><a href="<?=$row['url'];?>"><?=$row['name'];?></a></li>
				<?php } ?>
			</ul>
			<ul class="nav navbar-nav navbar-right">

				<li><a href="/cart"><?= __('Cart') ?> (<span id="cart-count"></span>)</a></li>

				<?php if ($vars['user']) { ?>
					<li><a href="/user/profile"><?= $vars['user']->login; ?></a></li>
					<li><a href="/user/logout"><? __('Logout') ?></a></li>
				<?php } else { ?>
					<li><a href="/user/login"><? __('Sign in') ?></a></li>
					<li><a href="/user/register"><? __('Register') ?></a></li>
				<?php } ?>

				<?php foreach ($vars['languages'] as $key => $lang) { ?>
					<li class="<?php echo $this->isCurrentLanguage($key) ? 'active' : ''; ?>">
						<a href="/lang/?switch=<?= $key; ?>"><?= strtoupper($key); ?></a>
					</li>
				<?php } ?>
			</ul>
		</div>
	</div>
</nav>
