<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
					data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">[Shop]</a>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<?php foreach ($vars['main_menu'] as $row) { ?>
					<li><a href="<?=$row['url'];?>"><?=$row['name'];?></a></li>
				<?php } ?>
			</ul>
			<ul class="nav navbar-nav navbar-right">

				<li><a href="/cart"><?= __('Cart') ?> (<span id="cart-count"></span>)</a></li>

				<?php if ($vars['user']) { ?>
					<li><a href="/user/profile"><?= $vars['user']->login; ?></a></li>
					<li><a href="/user/logout"><? __('Logout') ?></a></li>
				<?php } else { ?>
					<li><a href="/user/login"><? __('Sign in') ?></a></li>
					<li><a href="/user/register"><? __('Register') ?></a></li>
				<?php } ?>

				<li class="<?php echo $this->isCurrentLanguage('ru') ? 'active' : ''; ?>"><a
						href="/lang/?switch=ru">RU</a></li>
				<li class="<?php echo $this->isCurrentLanguage('en') ? 'active' : ''; ?>"><a
						href="/lang/?switch=en">EN</a></li>
			</ul>
		</div>
	</div>
</nav>
