<div class="row" xmlns="http://www.w3.org/1999/html">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Order details') ?> #<?=$vars['order']['id'];?></h3>
	</div>
</div>

<br/>
<div class="row">
	<div class="col-lg-12">
			<input type="hidden" name="id" value="<?= $vars['order']['id']; ?>"/>
			<div class="form-group">
				<label><?= __('Sum') ?></label>
				<input class="form-control" name="login" value="<?= $vars['order']['sum']; ?>" readonly />
			</div>
			<div class="form-group">
				<label><?= __('First name') ?></label>
				<input class="form-control" name="info[firstName]"
					   value="<?= $vars['order']['firstName']; ?>" readonly />
			</div>
			<div class="form-group">
				<label><?= __('Last name') ?></label>
				<input class="form-control" name="info[lastName]"
					   value="<?= $vars['order']['lastName']; ?>" readonly />
			</div>
			<div class="form-group">
				<label><?= __('Phone') ?></label>
				<input class="form-control" name="info[phone]" value="<?= $vars['order']['phone']; ?>" readonly/>
			</div>
			<div class="form-group">
				<label><?= __('Address') ?></label>
				<input class="form-control" name="info[address]" value="<?= $vars['order']['address']; ?>" readonly/>
			</div>
			<div class="form-group">
				<label><?= __('Comment') ?></label>
				<textarea class="form-control" name="comment" readonly><?= $vars['order']['comment']; ?></textarea>
			</div>
	</div>
</div>

<div class="row" xmlns="http://www.w3.org/1999/html">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Products') ?></h3>
	</div>
</div>

<div class="table-responsive">
	<form type="post" action="/cart/recalculate">
		<table class="table table-hover">
			<thead>
			<tr>
				<th>#</th>
				<th><?= __('Photo') ?></th>
				<th><?= __('Name') ?></th>
				<th><?= __('Count') ?></th>
				<th><?= __('Price') ?></th>
				<th><?= __('Sum') ?></th>
			</tr>
			</thead>
			<tbody>
			<?php $counter = 1; ?>
			<?php foreach ($vars['products'] as $item) { ?>
				<tr>
					<td><?= $counter++; ?></td>
					<td><img height="50" src="/api.php?method=Resource.get&id=<?= $item['photo_id']; ?>" /></td>
					<td><?= $item['name']; ?></td>
					<td><?= $item['count']; ?></td>
					<td><?= number_format($item['price'], 2); ?></td>
					<td><?= number_format($item['price'] * $item['count'], 2); ?></td>
				</tr>
			<?php } ?>
			<tr>
				<td colspan="5"></td>
				<td><?= number_format($vars['order']['sum'], 2); ?></td>
			</tr>
			</tbody>
		</table>
	</form>
</div>