<div class="row">
	<div class="col-lg-12">
		<?php echo $vars['breadcrumbs']; ?>
	</div>
</div>


<h1><?= $vars['product']['name']; ?></h1>
<img src="/api.php?method=Resource.get&id=<?=$vars['product']['photo_id'];?>" />

<br/><br/>
<p><b></b><?= __('Status') ?>:</b> <?= $vars['product']['status_text']; ?></p>
<p><?= htmlspecialchars_decode($vars['product']['text']); ?></p>
<p><b><?= \App\Service\Product::viewPrice($vars['product']['price']); ?></b></p>

<div class="form-group">
	<button class="btn btn-success" onclick="addToCart(<?=$vars['product']['id'];?>);"><?= __('Add to cart') ?></button>
</div>
<div class="form-group">
	<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#order-form"><?= __('Buy now') ?></button>
</div>

<?php include 'comments.phtml'; ?>

<!-- Modal -->
<div class="modal fade" id="order-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="myModalLabel"><?= __('Quick order form') ?></h4>
			</div>
			<div class="modal-body">
				<?php include 'quick_order_form.phtml' ;?>
			</div>
		</div>
	</div>
</div>
