<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header">Add new product</h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/product/save">
			<div class="form-group">
				<label>Name</label>
				<input class="form-control" name="name" value=""/>
			</div>
			<div class="form-group">
				<label>Catalog</label>
				<select class="form-control" name="catalog_id">
					<?php
					foreach ($vars['catalogs'] as $id => $name) {
						echo '<option value="' . $id . '">' . $name . '</option>';
					}
					?>
				</select>
			</div>
			<div class="form-group">
				<label>Url</label>
				<input class="form-control" name="url" value=""/>
			</div>
			<div class="form-group">
				<label>Text</label>
				<textarea id="editor-1" class="form-control" name="text"></textarea>
				<script>CKEDITOR.replace('editor-1');</script>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="Save"/>
				<input type="button" class="btn btn-primary" onclick="location.href='/admin/product';" value="Cancel"/>
			</div>
		</form>
	</div>
</div>
