<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Add new product') ?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/product/save">
			<div class="form-group">
				<label><?= __('Name') ?></label>
				<input class="form-control" name="name" value=""/>
			</div>
			<div class="form-group">
				<label><?= __('Catalog') ?></label>
				<select class="form-control" name="catalog_id">
					<?php
					foreach ($vars['catalogs'] as $id => $name) {
						echo '<option value="' . $id . '">' . $name . '</option>';
					}
					?>
				</select>
			</div>
			<div class="form-group">
				<label><?= __('Status') ?></label>
				<select class="form-control" name="status">
					<?php
					foreach ($vars['statuses'] as $id => $name) {
						echo '<option value="' . $id . '">' . $name . '</option>';
					}
					?>
				</select>
			</div>
			<div class="form-group">
				<label><?= __('Url') ?></label>
				<input class="form-control" name="url" value=""/>
			</div>
			<div class="form-group">
				<label><?= __('Short Description') ?></label>
				<textarea class="form-control" name="text_m"></textarea>
			</div>
			<div class="form-group">
				<label><?= __('Text') ?></label>
				<textarea id="editor-1" class="form-control" name="text"></textarea>
				<script>CKEDITOR.replace('editor-1');</script>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="<?= __('Save') ?>"/>
				<input type="button" class="btn btn-primary" onclick="location.href='/admin/product';" value="<?= __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>
