<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Edit product') ?> - <?= $vars['product']['name']; ?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div>

	<!-- Nav tabs -->
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#info" aria-controls="info" role="tab"
												  data-toggle="tab"><?= __('Information'); ?></a></li>
		<li role="presentation"><a href="#photos" aria-controls="photos" role="tab"
								   data-toggle="tab"><?= __('Photo'); ?></a></li>
		<li role="presentation"><a href="#filters" aria-controls="filters" role="tab"
								   data-toggle="tab"><?= __('Filters'); ?></a></li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane active" id="info">
			<div class="row">
				<div class="col-lg-12">
					<form role="form" action="/admin/product/save">
						<input type="hidden" name="id" value="<?= $vars['product']['id']; ?>"/>
						<div class="form-group">
							<label><?= __('Name') ?></label>
							<input class="form-control" name="name" value="<?= $vars['product']['name']; ?>"/>
						</div>
						<div class="form-group">
							<label><?= __('Catalog') ?></label>
							<select class="form-control" name="catalog_id">
								<?php
								foreach ($vars['catalogs'] as $id => $name) {
									$selected = ($vars['product']['catalog_id'] == $id) ? 'selected' : '';
									echo '<option ' . $selected . ' value="' . $id . '">' . $name . '</option>';
								}
								?>
							</select>
						</div>
						<div class="form-group">
							<label><?= __('Product categories') ?></label>
							<?php foreach ($vars['categories'] as $id => $row) { ?>
								<?php $checked = (in_array($id, $vars['product']['categories'])) ? 'checked="checked"' : ''; ?>
								<div class="checkbox">
									<label><input <?= $checked; ?> type="checkbox" name="categories[]" value="<?= $id; ?>"><?= $row['name']; ?></label>
								</div>
							<?php } ?>
						</div>
						<div class="form-group">
							<label><?= __('Url') ?></label>
							<input class="form-control" name="url" value="<?= $vars['product']['url']; ?>"/>
						</div>
						<div class="form-group">
							<label><?= __('Price') ?> (<?= \Admin\Utils::getBasicCurrency()->getValue('name'); ?>)</label>
							<input class="form-control" name="price" value="<?= $vars['product']['price']; ?>"/>
						</div>
						<div class="form-group">
							<label><?= __('Status') ?></label>
							<select class="form-control" name="status">
								<?php
								foreach ($vars['statuses'] as $id => $name) {
									$selected = ($vars['product']['status'] == $id) ? 'selected' : '';
									echo '<option ' . $selected . ' value="' . $id . '">' . $name . '</option>';
								}
								?>
							</select>
						</div>
						<div class="form-group">
							<label><?= __('Short Description') ?></label>
							<textarea class="form-control" name="text_m"><?= $vars['product']['text_m']; ?></textarea>
						</div>
						<div class="form-group">
							<label><?= __('Text') ?></label>
							<textarea id="editor-1" class="form-control" name="text"><?= $vars['product']['text']; ?></textarea>
						</div>
						<div class="form-group">
							<input type="submit" class="btn btn-success" value="<?= __('Save') ?>"/>
							<input type="button" class="btn btn-primary" onclick="location.href='/admin/product';"
								   value="<?= __('Cancel') ?>"/>
						</div>
					</form>
				</div>
			</div>
		</div>
		<div role="tabpanel" class="tab-pane" id="photos">
			<?= $vars['photo']; ?>
		</div>
		<div role="tabpanel" class="tab-pane" id="filters">

			<div class="dataTables_wrapper">
				<form role="form" action="/admin/product/savefilters">
					<input type="hidden" name="id" value="<?= $vars['product']['id']; ?>"/>
					<div class="row filters">
						<div class="col-lg-12">
							<table class="table table-bordered dataTable">
								<thead>
								<tr>
									<th>ID</th>
									<th><?= __('Name') ?></th>
									<th><?= __('Group') ?></th>
								</tr>
								</thead>
								<tbody>
								<?php
								foreach ($vars['filters'] as $row) {
									$checked = in_array($row['id'], $vars['set_filters']) ? 'checked' : '';
									echo '
								<tr>
									<td><input type="checkbox" name="filterId[]" value="' . $row['id'] . '" ' . $checked . '/></td>
									<td>' . $row['name'] . '</td>
									<td>' . $row['group'] . '</td>
								</tr>';
								}
								?>
								</tbody>
							</table>
						</div>
					</div>
					<div class="form-group">
						<input type="submit" class="btn btn-success" value="<?= __('Save') ?>"/>
						<input type="button" class="btn btn-primary" onclick="location.href='/admin/product';"
							   value="<?= __('Cancel') ?>"/>
					</div>

				</form>
			</div>


		</div>
	</div>
</div>

