<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header">Edit product - <?= $vars['product']['name']; ?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/product/save">
			<input type="hidden" name="id" value="<?= $vars['product']['id']; ?>"/>
			<div class="form-group">
				<label>Name</label>
				<input class="form-control" name="name" value="<?= $vars['product']['name']; ?>"/>
			</div>
			<div class="form-group">
				<label>Catalog</label>
				<select class="form-control" name="catalog_id">
					<?php
					foreach ($vars['catalogs'] as $id => $name) {
						$selected = ($vars['product']['catalog_id'] == $id) ? 'selected' : '';
						echo '<option ' . $selected . ' value="' . $id . '">' . $name . '</option>';
					}
					?>
				</select>
			</div>
			<div class="form-group">
				<label>Url</label>
				<input class="form-control" name="url" value="<?= $vars['product']['url']; ?>"/>
			</div>
			<div class="form-group">
				<label>Text</label>
				<textarea id="editor-1" class="form-control" name="text"><?= $vars['product']['text']; ?></textarea>
				<script>CKEDITOR.replace('editor-1');</script>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="Save"/>
				<input type="button" class="btn btn-primary" onclick="location.href='/admin/product';" value="Cancel"/>
			</div>
		</form>
	</div>
</div>
