<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Sign in') ?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/user/login" autocomplete="on">
			<div class="form-group">
				<label><?= __('Login') ?></label>
				<input class="form-control" name="login" value="" autofocus />
			</div>
			<div class="form-group">
				<label><?= __('Password') ?></label>
				<input class="form-control" name="password" value=""/>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="<?= __('Sign in') ?>"/>
			</div>
		</form>
	</div>
</div>
