<div class="row" xmlns="http://www.w3.org/1999/html">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Orders') ?></h3>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<ul class="nav nav-pills">
			<li role="presentation"><a href="/user"><?= __('Profile') ?></a></li>
			<li role="presentation" class="active"><a href="/order"><?= __('Orders') ?></a></li>
			<li role="presentation"><a href="/social_networks"><?= __('Social Networks') ?></a></li>
		</ul>
	</div>
</div>

<br/>

<div class="container-fluid">
	<div class="row">
		<div class="table-responsive">
			<table class="table table-hover">
				<thead>
				<tr>
					<th>#</th>
					<th><?= __('Date') ?></th>
					<th><?= __('Sum') ?></th>
					<th><?= __('Status') ?></th>
					<th><?= __('Actions') ?></th>
				</tr>
				</thead>
				<tbody>
				<?php $counter = 1; ?>
				<?php foreach ($vars['orders'] as $item) { ?>
					<tr>
						<td><?= $item['id']; ?></td>
						<td><?= $item['date']; ?></td>
						<td><?= $item['sum']; ?></td>
						<td><?= $item['status']; ?></td>
						<td><a href="/order/show/<?= $item['id']; ?>"><?= __('details'); ?></a></td>
					</tr>
				<?php } ?>
				</tbody>
			</table>
		</div>
	</div>