<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><? __('Profile') ?></h3>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<ul class="nav nav-pills">
			<li role="presentation" class="active"><a href="/user"><? __('Profile') ?></a></li>
			<li role="presentation"><a href="/order"><? __('Orders') ?></a></li>
		</ul>
	</div>
</div>

<br/>

<div class="row">
	<div class="col-lg-12">
		<form role="form" method="post" action="/user/save">
			<div class="form-group">
				<label><? __('Login') ?></label>
				<input class="form-control" name="login" value="<?= $vars['user']['login']; ?>" readonly />
			</div>
			<div class="form-group">
				<label><? __('E-Mail') ?></label>
				<input class="form-control" name="info[email]" value="<?= $vars['user']['info']['email']; ?>"/>
			</div>
			<div class="form-group">
				<label><? __('First name') ?></label>
				<input class="form-control" name="info[firstName]" value="<?= $vars['user']['info']['firstName']; ?>" />
			</div>
			<div class="form-group">
				<label><? __('Last name') ?></label>
				<input class="form-control" name="info[lastName]" value="<?= $vars['user']['info']['lastName']; ?>" />
			</div>
			<div class="form-group">
				<label><? __('Phone') ?></label>
				<input class="form-control" name="info[phone]" value="<?= $vars['user']['info']['phone']; ?>"/>
			</div>
			<div class="form-group">
				<label><? __('Address') ?></label>
				<input class="form-control" name="info[address]" value="<?= $vars['user']['info']['address']; ?>"/>
			</div>
			<div class="form-group">
				<label><? __('Password') ?></label>
				<input class="form-control" name="password" value="" />
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="<? __('Save') ?>"/>
			</div>
		</form>
	</div>
</div>
