<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><? __('Profile') ?></h3>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/profile/save">
			<div class="form-group">
				<label><? __('Login') ?></label>
				<input class="form-control" name="login" value="<?= $vars['user']['login']; ?>" readonly />
			</div>
			<div class="form-group">
				<label><? __('Password') ?></label>
				<input class="form-control" name="password" value="" />
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="<? __('Save') ?>"/>
			</div>
		</form>
	</div>
</div>
