<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><? __('Register') ?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/user/register" autocomplete="off">
			<div class="form-group">
				<label><? __('Login') ?></label>
				<input class="form-control" name="login" value=""/>
			</div>
			<div class="form-group">
				<label><? __('First name') ?></label>
				<input class="form-control" name="info[firstName]" value="" />
			</div>
			<div class="form-group">
				<label><? __('Last name') ?></label>
				<input class="form-control" name="info[lastName]" value="" />
			</div>
			<div class="form-group">
				<label><? __('Phone') ?></label>
				<input class="form-control" name="info[phone]" value="" />
			</div>
			<div class="form-group">
				<label><? __('Address') ?></label>
				<input class="form-control" name="info[address]" value="" />
			</div>
			<div class="form-group">
				<label><? __('Password') ?></label>
				<input class="form-control" name="password" value="" />
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="<? __('Register') ?>"/>
			</div>
		</form>
	</div>
</div>
