<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Edit catalog') ?> - <?=$vars['catalog']['name'];?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/catalog/save">
			<input type="hidden" name="id" value="<?= $vars['catalog']['id']; ?>"/>
			<div class="form-group">
				<label><?= __('Name') ?></label>
				<input class="form-control" name="name" value="<?= $vars['catalog']['name']; ?>"/>
			</div>
			<div class="form-group">
				<label><?= __('Photo') ?></label>
				<?=$vars['edit_photo'];?>
			</div>
			<div class="form-group">
				<label><?= __('Parent catalog') ?></label>
				<select name="parent" class="form-control">
					<option value="0">-</option>
					<?php foreach ($vars['all'] as $row) {
						$selected = ($row['id'] == $vars['catalog']['parent']) ? 'selected' : '';
						?>
						<option <?=$selected;?> value="<?=$row['id'];?>"><?=$row['name'];?></option>
					<?php } ?>
				</select>
			</div>
			<div class="form-group">
				<label><?= __('Url') ?></label>
				<input class="form-control" name="url" value="<?= $vars['catalog']['url']; ?>"/>
			</div>
			<div class="form-group">
				<label><?= __('Text') ?></label>
				<textarea id="editor-1" class="form-control" name="text"><?= $vars['catalog']['text']; ?></textarea>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="<?= __('Save') ?>"/>
				<input type="button" class="btn btn-primary" onclick="location.href='/admin/catalog';" value="<?= __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>

