<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"><?= __('Catalog') ?></h1>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<button class="btn btn-primary"
				onclick="location.href='/admin/catalog/new'"><?= __('Add new catalog') ?></button>
	</div>
</div>

<br/>

<div class="row">
	<div class="col-lg-3">
		<form method="get">
			<div class="form-group">
				<label><?= __('Parent catalog') ?></label>
				<select name="parent" class="form-control" onchange="submit();">
					<option value="0">-</option>
					<?php foreach ($vars['all'] as $row) {
						$selected = ($row['id'] == $vars['current']) ? 'selected' : '';
					?>
						<option <?=$selected;?> value="<?=$row['id'];?>"><?=$row['name'];?></option>
					<?php } ?>
				</select>
			</div>
		</form>
	</div>
</div>

<br/>
<div class="dataTable_wrapper">
	<div class="dataTables_wrapper">
		<div class="row">
			<div class="col-lg-12">
				<table class="table table-bordered dataTable">
					<thead>
					<tr>
						<th>ID</th>
						<th><?= __('Name') ?></th>
						<th><?= __('Url') ?></th>
						<th><?= __('Active') ?></th>
						<th><?= __('Actions') ?></th>
					</tr>
					</thead>
					<tbody>
					<?php
					foreach ($vars['catalogs'] as $row) {
						echo '
                        <tr>
                            <td>' . $row['id'] . '</td>
                            <td>' . $row['name'] . '</td>
                            <td>' . $row['url'] . '</td>
                            <td>' . _snippet('active', [$row['id'], 'catalog', $row['active']]) . '</td>
                            <td>' . _snippet('actions', [$row['id'], 'catalog', ['duplicate', 'delete']]) . '</td>
                        </tr>';
					}
					?>
					</tbody>
				</table>
			</div>
		</div>
		<?php echo $vars['paging']; ?>
	</div>
</div>
