<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"><?= __('Catalog') ?></h1>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<button class="btn btn-primary"
				onclick="location.href='/admin/catalog/new'"><?= __('Add new catalog') ?></button>
	</div>
</div>

<br/>

<div class="row">
	<div class="col-lg-3">
		<form method="get">
			<div class="form-group">
				<label><?= __('Parent catalog') ?></label>
				<select name="parent" class="form-control" onchange="submit();">
					<option value="0"><?= __('Root catalog'); ?></option>
					<?php foreach ($vars['all'] as $l1) {
						if (!$l1['parent']) {
							$selected = ($l1['id'] == $vars['current']) ? 'selected' : '';
							echo '<option ' . $selected . '  value="' . $l1['id'] . '">' . $l1['name'] . '</option>';

							foreach ($vars['all'] as $l2) {
								if ($l2['parent'] == $l1['id']) {
									$selected = ($l2['id'] == $vars['current']) ? 'selected' : '';

									foreach ($vars['all'] as $l3) {
										if ($l3['parent'] == $l2['id']) {
											$selected = ($l3['id'] == $vars['current']) ? 'selected' : '';
											echo '<option ' . $selected . '  value="' . $l3['id'] . '"> - ' . $l3['name'] . '</option>';
										}
									}

									echo '<option ' . $selected . '  value="' . $l2['id'] . '"> - ' . $l2['name'] . '</option>';
								}
							}
						}
					 } ?>
				</select>
			</div>
		</form>
	</div>
</div>

<br/>
<div class="dataTable_wrapper">
	<div class="dataTables_wrapper">
		<div class="row">
			<div class="col-lg-12">
				<table class="table table-bordered dataTable">
					<thead>
					<tr>
						<th>ID</th>
						<th><?= __('Name') ?></th>
						<th><?= __('Url') ?></th>
						<th><?= __('Active') ?></th>
						<th><?= __('Actions') ?></th>
					</tr>
					</thead>
					<tbody>
					<?php
					foreach ($vars['catalogs'] as $row) {
						echo '
                        <tr>
                            <td>' . $row['id'] . '</td>
                            <td>' . $row['name'] . '</td>
                            <td>' . $row['url'] . '</td>
                            <td>' . _snippet('active', [$row['id'], 'catalog', $row['active']]) . '</td>
                            <td>' . _snippet('actions', [$row['id'], 'catalog', ['duplicate', 'delete']]) . '</td>
                        </tr>';
					}
					?>
					</tbody>
				</table>
			</div>
		</div>
		<?php echo $vars['paging']; ?>
	</div>
</div>
