<div class="row">
	<div class="col-lg-12">
		<?php echo $vars['breadcrumbs']; ?>
	</div>
</div>


<h1><?= __('Catalog'); ?></h1>

<div class="row">
	<div class="col-lg-2">
		<ul class="nav nav-pills nav-stacked">
			<li role="presentation"><a href="/catalog/"><?= __('All categories') ?></a></li>
			<?php
			foreach ($vars['catalogs'] as $cat) {
				$active = ($cat['id'] == $vars['catalog']) ? 'class="active"' : '';
				echo '<li role="presentation" ' . $active . '><a href="/catalog/view/' . $cat['url'] . '">' . $cat['name'] . '</a></li>';
			}
			?>
		</ul>

		<div id="products-filters">
			<?php include 'products_filters.phtml'; ?>
		</div>
	</div>

	<div class="col-lg-10">
		<div class="row">
			<?php include 'products_sort.phtml'; ?>
		</div>
		<div class="row">
			<div id="products-list">
				<?php include 'products_list.phtml'; ?>
			</div>
		</div>
	</div>
</div>

<script>
	$('#products-filters').on('click', function (e) {
		if ($(e.target).hasClass('filter')) {
			requestProducts(<?=$vars['catalog']?>);
		}
	});

	$('#products-sort').on('change', function () {
		requestProducts(<?=$vars['catalog']?>);
	});
</script>
