<div class="col-lg-4">
	<div class="form-group">
		<label><? __('Sorting') ?></label>
		<select class="form-control" name="sort" id="products-sort">
			<option <?= ($vars['sort'] == '') ? 'selected' : '' ?> value=""><? __('default') ?></option>
			<option <?= ($vars['sort'] == 'price:asc') ? 'selected' : '' ?> value="price:asc"><? __('from lower price') ?></option>
			<option <?= ($vars['sort'] == 'price:desc') ? 'selected' : '' ?> value="price:desc"><? __('from higher price') ?></option>
		</select>
	</div>
</div>