<div class="col-md-3 col-sm-6">
	<div class="product-col">
		<div class="image">
			<a href="/product/view/<?= $product['url']; ?>">
				<img class="product-unpreview-hide img-responsive" src="/api.php?method=Resource.get&id=<?= $product['photo_id']; ?>" alt="product" />
				<img class="product-preview-hide img-responsive" src="/api.php?method=Resource.get&id=<?= $product['photo_id2']; ?>" alt="product" />
			</a>
		</div>
		<div class="caption">
			<h4>
				<a href="/product/view/<?= $product['url']; ?>"><?= (strlen($product['name']) > 22) ? mb_substr($product['name'], 0, 22) . '...' : $product['name']; ?></a>
			</h4>
			<div class="price">
				<?php if ($product['old_price'] > 0) { ?>
					<span class="price-old"><?= \App\Service\Product::viewPrice($product['old_price']); ?></span>
				<?php } ?>
				<span class="price-new"><?= \App\Service\Product::viewPrice($product['price']); ?></span>
			</div>

			<div class="product-preview">
				<div class="description">
					<?= $product['text_m']; ?>
				</div>

				<div class="cart-button button-group">
					<a type="button" class="btn btn-cart" href="/product/view/<?= $product['url']; ?>">
						<?= __('Details'); ?>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
