<div class="btn-group">
	<button class="btn btn-link dropdown-toggle" data-toggle="dropdown">
		<?= strtoupper(\Core\Config::get('site.language')); ?>
		<i class="fa fa-caret-down"></i>
	</button>
	<ul class="pull-left dropdown-menu">
		<?php foreach ($vars['languages'] as $key => $lang) { ?>
			<li><a tab-index="-1" href="/lang/?switch=<?= $key; ?>"><?= $lang; ?></a></li>
		<?php } ?>
	</ul>
</div>