<div class="form-group">
	<label><? __($vars['name']); ?></label>
	<select name="<?= $vars['name']; ?>" id="selectize-<?= $vars['count']; ?>" multiple>
		<?php
		foreach ($vars['options'] as $key => $val) {
			$selected = ($key == $vars['value']) ? ' selected="selected" ' : '';
			echo '<option value="' . $key . '" ' . $selected . '>' . $val . '</option>';
		}
		?>
	</select>
</div>
<script>
	$("#selectize-<?= $vars['count']; ?>").selectize({
		plugins: ['remove_button']
	});
</script>