<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><? __('Edit user') ?> - <?=$vars['user']['login'];?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/user/save">
			<input type="hidden" name="id" value="<?= $vars['user']['id']; ?>"/>
			<div class="form-group">
				<label><? __('Login') ?></label>
				<input class="form-control" name="login" value="<?= $vars['user']['login']; ?>"/>
			</div>
			<div class="form-group">
				<label><? __('First name') ?></label>
				<input class="form-control" name="info[firstName]" value="<?= $vars['user']['info']['firstName']; ?>" />
			</div>
			<div class="form-group">
				<label><? __('Last name') ?></label>
				<input class="form-control" name="info[lastName]" value="<?= $vars['user']['info']['lastName']; ?>" />
			</div>
			<div class="form-group">
				<label><? __('Phone') ?></label>
				<input class="form-control" name="info[phone]" value="<?= $vars['user']['info']['phone']; ?>"/>
			</div>
			<div class="form-group">
				<label><? __('Address') ?></label>
				<input class="form-control" name="info[address]" value="<?= $vars['user']['info']['address']; ?>"/>
			</div>
			<div class="form-group">
				<label><? __('Password') ?></label>
				<input class="form-control" name="password" value="" />
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-default" value="<? __('Save') ?>"/>
				<input type="button" class="btn btn-cancel" onclick="location.href='/admin/user';" value="<? __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>
