<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><? __('Edit user') ?> - <?=$vars['user']['name'];?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/user/save">
			<input type="hidden" name="id" value="<?= $vars['user']['id']; ?>"/>
			<div class="form-group">
				<label><? __('Login') ?></label>
				<input class="form-control" name="name" value="<?= $vars['user']['login']; ?>"/>
			</div>
			<div class="form-group">
				<label><? __('Password') ?></label>
				<input class="form-control" name="url" value="<?= $vars['user']['password']; ?>"/>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-default" value="<? __('Save') ?>"/>
				<input type="button" class="btn btn-cancel" onclick="location.href='/admin/user';" value="<? __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>
