<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><? __('Edit menu item') ?> - <?= $vars['menu']['name']; ?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/menu/save">
			<input type="hidden" name="id" value="<?= $vars['menu']['id']; ?>"/>
			<div class="form-group">
				<label><? __('Name') ?></label>
				<input class="form-control" name="name" value="<?= $vars['menu']['name']; ?>"/>
			</div>
			<div class="form-group">
				<label><? __('Type') ?></label>
				<select class="form-control" name="type">
					<?php
					foreach ($vars['types'] as $id => $name) {
						$selected = ($vars['menu']['type'] == $id) ? 'selected' : '';
						echo '<option ' . $selected . ' value="' . $id . '">' . $name . '</option>';
					}
					?>
				</select>
			</div>
			<div class="form-group">
				<label><? __('Url') ?></label>
				<input class="form-control" name="url" value="<?= $vars['menu']['url']; ?>"/>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-default" value="<? __('Save') ?>"/>
				<input type="button" class="btn btn-cancel" onclick="location.href='/admin/menu';" value="<? __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>
