<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Edit menu item') ?> - <?= $vars['menu']['name']; ?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/menu/save">
			<input type="hidden" name="id" value="<?= $vars['menu']['id']; ?>"/>
			<div class="form-group">
				<label><?= __('Name') ?></label>
				<input class="form-control" name="name" value="<?= $vars['menu']['name']; ?>"/>
			</div>
			<div class="form-group">
				<label><?= __('Type') ?></label>
				<select class="form-control" name="type">
					<?php
					foreach ($vars['types'] as $id => $name) {
						$selected = ($vars['menu']['type'] == $id) ? 'selected' : '';
						echo '<option ' . $selected . ' value="' . $id . '">' . $name . '</option>';
					}
					?>
				</select>
			</div>
			<div class="form-group">
				<label><?= __('Parent menu') ?></label>
				<select name="parent" class="form-control">
					<option value="0">-</option>
					<?php foreach ($vars['all'] as $row) {
						$selected = ($row['id'] == $vars['menu']['parent']) ? 'selected' : '';
						?>
						<option <?=$selected;?> value="<?=$row['id'];?>"><?=$row['name'];?></option>
					<?php } ?>
				</select>
			</div>
			<div class="form-group">
				<label><?= __('Url') ?></label>
				<input class="form-control" name="url" value="<?= $vars['menu']['url']; ?>"/>
			</div>
			<div class="form-group">
				<label><?= __('Icon') ?> (<i id="icon-preview" class="fa fa-fw <?= $vars['menu']['icon']; ?>"></i>) </label>
				<input class="form-control icon-bind" name="icon" value="<?= $vars['menu']['icon']; ?>"/>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-default" value="<?= __('Save') ?>"/>
				<input type="button" class="btn btn-cancel" onclick="location.href='/admin/menu';" value="<?= __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>

<script>
	$('.icon-bind').on('keyup', function () {
		$('#icon-preview').attr('class', "fa fa-fw " + $(this).val());
	})
</script>