<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"><? __('Menu') ?></h1>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<button class="btn btn-primary" onclick="location.href='/admin/menu/new'"><? __('Add new menu item') ?></button>
	</div>
</div>

<br/>
<div class="dataTable_wrapper">
	<div class="dataTables_wrapper">
		<div class="row">
			<div class="col-lg-12">
				<table class="table table-bordered dataTable">
					<thead>
					<tr>
						<th>ID</th>
						<th><? __('Name') ?></th>
						<th><? __('Url') ?></th>
						<th><? __('Type') ?></th>
						<th><? __('Active') ?></th>
						<th><? __('Actions') ?></th>
					</tr>
					</thead>
					<tbody>
					<?php
					foreach ($vars['menu']->getCollection() as $menu) {
						echo '
                        <tr>
                            <td>' . $menu->id . '</td>
                            <td>' . $menu->name . '</td>
                            <td>' . $menu->url . '</td>
                            <td>' . $menu->getMenuType() . '</td>
                            <td>' . _snippet('active', [$menu->id, 'menu', $menu->active]) . '</td>
                            <td>' . _snippet('actions', [$menu->id, 'menu', ['duplicate', 'delete']]) . '</td>
                        </tr>';
					}
					?>
					</tbody>
				</table>
			</div>
		</div>
		<?php echo $vars['paging']; ?>
	</div>
</div>
