<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><? __('Add new order') ?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/order/save">
			<div class="form-group">
				<label><? __('Sum') ?></label>
				<input class="form-control" name="login" value="<?= $vars['order']['sum']; ?>"/>
			</div>
			<div class="form-group">
				<label><? __('First name') ?></label>
				<input class="form-control" name="info[firstName]" value="<?= $vars['order']['firstName']; ?>" />
			</div>
			<div class="form-group">
				<label><? __('Last name') ?></label>
				<input class="form-control" name="info[lastName]" value="<?= $vars['order']['lastName']; ?>" />
			</div>
			<div class="form-group">
				<label><? __('Phone') ?></label>
				<input class="form-control" name="info[phone]" value="<?= $vars['order']['phone']; ?>"/>
			</div>
			<div class="form-group">
				<label><? __('Address') ?></label>
				<input class="form-control" name="info[address]" value="<?= $vars['order']['address']; ?>"/>
			</div>
			<div class="form-group">
				<label><? __('Comment') ?></label>
				<textarea class="form-control" name="comment"><?= $vars['order']['comment']; ?></textarea>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="<? __('Save') ?>"/>
				<input type="button" class="btn btn-primary" onclick="location.href='/admin/order';" value="<? __('Cancel') ?>"/>
			</div>
		</form>
	</div>
</div>
