<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Edit order') ?> - #<?= $vars['order']['id']; ?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div>
	<!-- Nav tabs -->
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#info" aria-controls="info" role="tab" data-toggle="tab"><?= __('Information'); ?></a></li>
		<li role="presentation"><a href="#products" aria-controls="products" role="tab"  data-toggle="tab"><?= __('Products'); ?></a></li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane active" id="info">
			<div class="row">
				<div class="col-lg-12">
					<form role="form" action="/admin/order/save">
						<input type="hidden" name="id" value="<?= $vars['order']['id']; ?>"/>
						<div class="form-group">
							<label><?= __('Sum') ?></label>
							<input class="form-control" name="login" value="<?= $vars['order']['sum']; ?>"/>
						</div>
						<div class="form-group">
							<label><?= __('Status') ?></label>
							<select class="form-control" name="status">
								<?php
								foreach ($vars['statuses'] as $id => $name) {
									$selected = ($vars['order']['status'] == $id) ? 'selected' : '';
									echo '<option ' . $selected . ' value="' . $id . '">' . $name . '</option>';
								}
								?>
							</select>
						</div>
						<div class="form-group">
							<label><?= __('First name') ?></label>
							<input class="form-control" name="info[firstName]"
								   value="<?= $vars['order']['firstName']; ?>"/>
						</div>
						<div class="form-group">
							<label><?= __('Last name') ?></label>
							<input class="form-control" name="info[lastName]"
								   value="<?= $vars['order']['lastName']; ?>"/>
						</div>
						<div class="form-group">
							<label><?= __('E-Mail') ?></label>
							<input class="form-control" name="info[email]" value="<?= $vars['order']['email']; ?>"/>
						</div>
						<div class="form-group">
							<label><?= __('Phone') ?></label>
							<input class="form-control" name="info[phone]" value="<?= $vars['order']['phone']; ?>"/>
						</div>
						<div class="form-group">
							<label><?= __('City') ?></label>
							<input class="form-control" name="info[city]" value="<?= $vars['order']['city']; ?>"/>
						</div>
						<div class="form-group">
							<label><?= __('Address') ?></label>
							<input class="form-control" name="info[address]" value="<?= $vars['order']['address']; ?>"/>
						</div>
						<div class="form-group">
							<label><?= __('Information') ?></label>
							<textarea class="form-control" name="info" rows="5"><?= $vars['order']['info']; ?></textarea>
						</div>
						<div class="form-group">
							<label><?= __('Comment') ?></label>
							<textarea class="form-control" name="comment" rows="5"><?= $vars['order']['comment']; ?></textarea>
						</div>

						<div class="form-group">
							<input type="submit" class="btn btn-default" value="<?= __('Save') ?>"/>
							<input type="button" class="btn btn-cancel" onclick="location.href='/admin/order';"
								   value="<?= __('Cancel') ?>"/>
						</div>
					</form>
				</div>
			</div>
		</div>
		<div role="tabpanel" class="tab-pane" id="products">
			<div class="row">
				<div class="col-lg-12">
					<?= $vars['products']; ?>
				</div>
			</div>
		</div>
	</div>
</div>