<form class="form form-horizontal" action="/admin/order/update" method="post">
	<input type="hidden" name="id" value="<?= $vars['orderId']; ?>"/>
	<label><?= __('Products') ?></label>
	<div class="dataTable_wrapper">
		<div class="dataTables_wrapper">
			<div class="row">
				<div class="col-lg-12">
					<table class="table table-bordered dataTable">
						<thead>
						<tr>
							<th>ID</th>
							<th><?= __('Name') ?></th>
							<th><?= __('Count') ?></th>
							<th><?= __('Price') ?></th>
							<th><?= __('Actions') ?></th>
						</tr>
						</thead>
						<tbody>
						<?php foreach ($vars['products'] as $var) { ?>
							<tr>
								<td><?= $var['id']; ?></td>
								<td><?= $var['name']; ?></td>
								<td>
									<input type="text" name="product[<?= $var['id']; ?>]"
										   value="<?= $var['count']; ?>"/>
								</td>
								<td><?= number_format($var['price'], 2); ?></td>
								<td><a class="remove-from-order" data-id="<?=$var['id'];?>" href="#">x</a></td>
							</tr>
						<?php } ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>


	<div class="col-lg-12">
		<div class="form-group">
			<label><?= __('Add more products') ?></label>
			<div class="row">
				<div class="col-lg-11">
					<select class="form-control product-search" placeholder="<?= __('Search'); ?>"></select>
				</div>
				<div class="col-lg-1">
					<input type="button" class="btn btn-primary add-to-order" value="<?= __('Add') ?>"/>
				</div>
			</div>
		</div>

		<div class="form-group">
			<input type="submit" class="btn btn-success" value="<?= __('Save') ?>"/>
		</div>
	</div>

</form>

<script>
	$(document).ready(function () {
		$('.product-search').selectize({
			valueField: 'id',
			labelField: 'name',
			searchField: 'name',
			load: function (query, callback) {
				if (!query.length) return callback();
				$.ajax({
					url: '/admin/api.php?method=Product.search&query=' + encodeURIComponent(query),
					type: 'GET',
					error: function () {
						callback();
					},
					success: function (res) {
						callback(res.response);
					}
				});
			}
		});

		$('.add-to-order').on('click', function () {
			var productId = $('.product-search').val();
			if (!productId) return;

			$.ajax({
				url: '/admin/api.php?method=Order.addProduct',
				data: {
					productId: productId,
					orderId: <?=$vars['orderId']; ?>,
				},
				type: 'POST',
				error: function () {
					//
				},
				success: function () {
					window.location.reload();
				}
			});

		});

		$('.remove-from-order').on('click', function () {
			var productId = $(this).data('id');
			if (!productId) return;

			$.ajax({
				url: '/admin/api.php?method=Order.removeProduct',
				data: {
					productId: productId,
					orderId: <?=$vars['orderId']; ?>,
				},
				type: 'POST',
				error: function () {
					//
				},
				success: function () {
					window.location.reload();
				}
			});

		});
	})
</script>