<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Edit slide') ?> - <?= $vars['slide']['name']; ?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div>

	<!-- Nav tabs -->
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#info" aria-controls="info" role="tab" data-toggle="tab"><?= __('Information') ;?></a></li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane active" id="info">
			<div class="row">
			<div class="col-lg-12">
				<form role="form" action="/admin/slider/save">
					<input type="hidden" name="id" value="<?= $vars['slide']['id']; ?>"/>
					<div class="form-group">
						<label><?= __('Name') ?></label>
						<input class="form-control" name="name" value="<?= $vars['slide']['name']; ?>"/>
					</div>
					<div class="form-group">
						<label><?= __('Photo') ?></label>
						<?=$vars['edit_photo'];?>
					</div>
					<div class="form-group">
						<label><?= __('Url') ?></label>
						<input class="form-control" name="url" value="<?= $vars['slide']['url']; ?>"/>
					</div>
					<div class="form-group">
						<label><?= __('Text') ?></label>
						<textarea id="editor-1" class="form-control" name="text"><?= $vars['slide']['text']; ?></textarea>
						<script>CKEDITOR.replace('editor-1');</script>
					</div>
					<div class="form-group">
						<input type="submit" class="btn btn-success" value="<?= __('Save') ?>"/>
						<input type="button" class="btn btn-primary" onclick="location.href='/admin/slider';" value="<?= __('Cancel') ?>"/>
					</div>
				</form>
			</div>
			</div>
		</div>
	</div>
</div>

