<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header">Add new translation</h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/translation/save">
			<div class="form-group">
				<label>Alias</label>
				<input class="form-control" name="alias" value=""/>
			</div>
			<div class="form-group">
				<label>Translation</label>
				<input class="form-control" name="value" value=""/>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="Save"/>
				<input type="button" class="btn btn-primary" onclick="location.href='/admin/traslation';" value="Cancel"/>
			</div>
		</form>
	</div>
</div>
