<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><?= __('Edit translation') ?> - <?=$vars['translation']['alias'];?></h3>
	</div>
</div>

<?php echo $this->getNotices(); ?>

<div class="row">
	<div class="col-lg-12">
		<form role="form" action="/admin/translation/save">
			<input type="hidden" name="id" value="<?= $vars['translation']['id']; ?>"/>
			<div class="form-group">
				<label><?= __('Alias') ?></label>
				<input class="form-control" name="alias" value="<?= $vars['translation']['alias']; ?>"/>
			</div>
			<div class="form-group">
				<label><?= __('Translation') ?></label>
				<input class="form-control" name="value" value="<?= $vars['translation']['value']; ?>"/>
			</div>
			<div class="form-group">
				<label><?= __('Type') ?></label>
				<select class="form-control" name="type">
					<option value="admin" <? if ($vars['translation']['type'] == 'admin') echo 'selected'; ?> ><?= __('Dashboard') ?></option>
					<option value="app" <? if ($vars['translation']['type'] == 'app') echo 'selected'; ?>><?= __('Site') ?></option>
				</select>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value="<?= __('Save') ?>"/>
				<input type="button" class="btn btn-primary" onclick="location.href='/admin/translation';" value="<?= __('Cancel') ?>" />
			</div>
		</form>
	</div>
</div>

