<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"><? __('Translation') ?></h1>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<button class="btn btn-primary"
				onclick="location.href='/admin/catalog/new'"><? __('Add new catalog') ?></button>
	</div>
</div>

<br/>
<div class="dataTable_wrapper">
	<div class="dataTables_wrapper">
		<div class="row">
			<div class="col-lg-12">
				<table class="table table-bordered dataTable">
					<thead>
					<tr>
						<th>ID</th>
						<th><? __('Alias') ?></th>
						<th><? __('Translation') ?></th>
						<th><? __('Actions') ?></th>
					</tr>
					</thead>
					<tbody>
					<?php
					foreach ($vars['catalogs'] as $row) {
						echo '
                        <tr>
                            <td>' . $row['id'] . '</td>
                            <td>' . $row['alias'] . '</td>
                            <td>' . (isset($row['value']) ? $row['value'] : '-') . '</td>
                            <td>' . _snippet('actions', [$row['id'], 'translation', ['delete']]) . '</td>
                        </tr>';
					}
					?>
					</tbody>
				</table>
			</div>
		</div>
		<?php echo $vars['paging']; ?>
	</div>
</div>
